# Load data

In [2]:
import pandas as pd
combined_df = pd.read_csv('combined_all_preop_index_new_refined_limonadi_251024.csv')
# combined_df = combined_df.drop(columns=['CombinedUpperExtremityWeak_preop','CombinedLowerExtremityWeak_preop','CombinedUpperDLTExtremities_preop','CombinedLowerDLTExtremities_preop',
#                                          'CombinedUpperExtremityStrength',
#  'CombinedLowerExtremityStrength',
#  'CombinedUpperDLTExtremity',
#  'CombinedLowerDLTExtremity'])
combined_df = combined_df.drop(columns=[col for col in combined_df.columns if 'Combined' in col])

In [3]:
combined_df[combined_df['Preop_HearingLoss']==0][['Preop_HearingLoss','Index_HearingLoss','New_HearingLoss','Refined_HearingLoss']]

,Preop_HearingLoss,Index_HearingLoss,New_HearingLoss,Refined_HearingLoss
0,0,5.0,5.0,3.0
1,0,1.0,0.0,3.0
2,0,1.0,0.0,3.0
3,0,3.0,0.0,3.0
4,0,1.0,0.0,3.0
...,...,...,...,...
157,0,5.0,5.0,3.0
158,0,3.0,0.0,3.0
159,0,5.0,5.0,3.0
160,0,1.0,0.0,3.0
161,0,1.0,0.0,3.0

In [4]:
list(combined_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [5]:
combined_df['Preop_Hoarseness_x'].value_counts()

Preop_Hoarseness_x
0    159
1      3
Name: count, dtype: int64

In [6]:
list(combined_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [7]:
combined_df.Allocation.value_counts()

Allocation
PFD     84
PFDD    78
Name: count, dtype: int64

In [8]:
preop_to_refined_neuro_map = {
    "Preop_Papilledema": "Refined_Papilledema",
    "Preop_Nystagmus": "Refined_Nystagmus",
    "Preop_DisconjugateGaze": "Refined_DisconjugateGaze",
    "Preop_ExtraocularPalsies": "Refined_DocExtraOcPalsies",
    "Preop_FacialWeakness": "Refined_FacialWeakness",
    "Preop_DisturbanceInFacialSensation": "Refined_DisturbanceFacSen",
    "Preop_HearingLoss": "Refined_HearingLoss",
    "Preop_Hoarseness_x": "Refined_Hoarseness",
    "Preop_TongueDeviation": "Refined_TongueDeviation",
    "Preop_WeakShrug": "Refined_WeakShrug",

    "Preop_LeftUpperExtremityWeak": "Refined_LeftUpperExtremityStrength",
    "Preop_RightUpperExtremityWeak": "Refined_RightUpperExtremityStrength",
    "Preop_LeftLowerExtremityWeak": "Refined_LeftLowerExtremityStrength",
    "Preop_RightLowerExtremityWeak": "Refined_RightLowerExtremityStrength",

    "Preop_LighttouchEntireBody": "Refined_DeficitToLightTouchEntireBody",
    "Preop_DLTLeftUpperExtremities": "Refined_LightTouchSensoryDeficitLUE",
    "Preop_DLTRightUpperExtremities": "Refined_LightTouchSensoryDeficitRUE",
    "Preop_DLTLeftLowerExtremities": "Refined_LightTouchSensoryDeficitLLE",
    "Preop_DLTRightLowerExtremities": "Refined_LightTouchSensoryDeficitRLE",

    "Preop_DeficitToPinprickUpperLeft": "Refined_LUEDeficitPinprick",
    "Preop_DeficitToPinprickUpperRight": "Refined_RUEDeficitPinprick",
    "Preop_DeficittoPinprickLowerLeft": "Refined_LLEDeficitPinprick",
    "Preop_DeficittoPinprickLowerRight": "Refined_RLEDeficitPinprick",

    "Preop_LightTouchTorso": "Refined_DeficitLightTouchTorso",
    "Preop_LightTouchSaddle": "Refined_DeficitLIghtTouchSaddle",

    "Preop_DeepTendonReflexes": "Refined_DeepTendonReflexes",
    "Preop_AnkleClonus": "Refined_FUAnkleClonus",
    "Preop_GaitInstability": "Refined_GaitStatus",
}

In [9]:

pfd_df = combined_df[combined_df['Allocation'] == 'PFD'].copy()
pfdd_df = combined_df[combined_df['Allocation'] == 'PFDD'].copy()


pfd_df = pfd_df.dropna(subset=['SubjectId'])
pfdd_df = pfdd_df.dropna(subset=['SubjectId'])


print("PFD group:", pfd_df.shape)
print("PFDD group:", pfdd_df.shape)

PFD group: (84, 290)
PFDD group: (78, 290)

In [10]:
pfdd_df['Preop_Hoarseness_x'].value_counts()

Preop_Hoarseness_x
0    77
1     1
Name: count, dtype: int64

In [11]:
pfd_df[pfd_df['Refined_GaitStatus']==2][['SubjectId','Preop_GaitInstability','Index_GaitStatus','Refined_GaitStatus']]

Empty DataFrame
Columns: [SubjectId, Preop_GaitInstability, Index_GaitStatus, Refined_GaitStatus]
Index: []

In [12]:
list(pfd_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [13]:
list(pfd_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [14]:
# desired_column = ['SubjectId',
#  'Papilledema_preop',
#  'Nystagmus_preop',
#  'DisconjugateGaze_preop',
#  'ExtraocularPalsies_preop',
#  'FacialWeakness_preop',
#  'DisturbanceInFacialSensation_preop',
#  'HearingLoss_preop',
#  'Hoarseness_preop',
#  'TongueDeviation_preop',
#  'WeakShrug_preop',
                  
#  'CombinedUpperExtremityWeak_preop',
#  'LeftUpperExtremityWeak_preop',
#  'RightUpperExtremityWeak_preop',
                  
#  'CombinedLowerExtremityWeak_preop',                  
#  'LeftLowerExtremityWeak_preop',
#  'RightLowerExtremityWeak_preop',
                  
#  'LighttouchEntireBody_preop',
                  
#  'CombinedUpperDLTExtremities_preop',                  
#  'DLTLeftUpperExtremities_preop',
#  'DLTRightUpperExtremities_preop',
                  
#  'CombinedLowerDLTExtremities_preop',                  
#  'DLTLeftLowerExtremities_preop',
#  'DLTRightLowerExtremities_preop',

#  'DeficitToPinprickUpperLeft_preop',
#  'DeficitToPinprickUpperRight_preop',
#  'DeficittoPinprickLowerLeft_preop',
#  'DeficittoPinprickLowerRight_preop',
#  'LightTouchTorso_preop',
#  'LightTouchSaddle_preop',
#  'DeepTendonReflexes_preop',
#  'AnkleClonus_preop',
#  'GaitInstability_preop',
#  'Papilledema',
#  'Nystagmus',
#  'DisconjugateGaze',
#  'DocExtraOcPalsies',
#  'FacialWeakness',
#  'DisturbanceFacSen',
#  'HearingLoss',
#  'Hoarseness_x',
#  'TongueDeviation',
#  'WeakShrug',
                  

#  'CombinedUpperExtremityStrength',                  
#  'LeftUpperExtremityStrength',
#  'RightUpperExtremityStrength',

#  'CombinedLowerExtremityStrength',
#  'LeftLowerExtremityStrength',
#  'RightLowerExtremityStrength',
#  'DeficitToLightTouchEntireBody',
                  
#  'CombinedUpperDLTExtremity',
#  'LightTouchSensoryDeficitLUE',
#  'LightTouchSensoryDeficitRUE',
                  
#  'CombinedLowerDLTExtremity',                  
#  'LightTouchSensoryDeficitLLE',
#  'LightTouchSensoryDeficitRLE',
                  
#  'LUEDeficitPinprick',
#  'RUEDeficitPinprick',
#  'LLEDeficitPinprick',
#  'RLEDeficitPinprick',
#  'DeficitLightTouchTorso',
#  'DeepTendonReflexes',
#  'FUAnkleClonus',
#  'GaitStatus',
#  'Site',





#  'Allocation']
# # Flatten the nested list if needed
# if isinstance(desired_column[0], list):
#     desired_column = desired_column[0]

# # Reorder with matching columns only
# existing_cols = [col for col in desired_column if col in pfd_df.columns]

# # Reorder pfd_df
# pfd_df_new = pfd_df[existing_cols]

# # Flatten the nested list if needed
# if isinstance(desired_column[0], list):
#     desired_column = desired_column[0]

# # Reorder with matching columns only
# existing_cols = [col for col in desired_column if col in pfdd_df.columns]

# # Reorder pfd_df
# pfdd_df_new = pfdd_df[existing_cols]

In [15]:
# pfd_df = pfd_df_new.copy()

In [16]:
# pfd_df

In [17]:
# pfdd_df = pfdd_df_.copy()

In [18]:
# list(pfd_df)

In [19]:
# pfd_df['LeftUpperExtremityWeak_preop'].value_counts()

In [20]:
# Function to generate summary table for a given group
def summarize_symptoms(df, label='Group'):
    all_summaries = []

    for pre_symptom, post_symptom in preop_to_refined_neuro_map.items():
        print(pre_symptom)
        # filter with preoperatove data
        pre_symptom = pre_symptom+''
        subset = df[df[pre_symptom] == False]
        baseline_count = subset['SubjectId'].nunique()

        temp = subset[['SubjectId', post_symptom]].fillna(0)
        temp = temp.rename(columns={post_symptom: 'Outcome'})
        temp['Outcome'] = temp['Outcome']
        temp['Symptom'] = pre_symptom
#        print(temp.Outcome.value_counts())
        count_df = temp.groupby('Outcome')['SubjectId'].nunique().reset_index()
        count_df['Symptom'] = pre_symptom
        count_df = count_df.rename(columns={'SubjectId': 'N_Patients'})
        count_pivot = count_df.pivot(index='Symptom', columns='Outcome', values='N_Patients')
        count_pivot['NotPresentBaseline'] = baseline_count
#        print(count_pivot)
        all_summaries.append(count_pivot)

# ---- Combine Left and Right Extremities ----

    # Define logical groupings of left/right into higher-level symptoms
    combo_groups = {
        'Preop_CombinedUpperExtremityWeak': ['Preop_LeftUpperExtremityWeak', 'Preop_RightUpperExtremityWeak'],
        'Preop_CombinedLowerExtremityWeak': ['Preop_LeftLowerExtremityWeak', 'Preop_RightLowerExtremityWeak'],
        'Preop_CombinedUpperDLTExtremity': ['Preop_DLTLeftUpperExtremities', 'Preop_DLTRightUpperExtremities'],
        'Preop_CombinedLowerDLTExtremity': ['Preop_DLTLeftLowerExtremities', 'Preop_DLTRightLowerExtremities'],
    }

    for new_symptom, sub_symptoms in combo_groups.items():
        # Get preop columns
        preop_cols = [s + "" for s in sub_symptoms]

        # Subjects who had any pre-op indication

        # Subjects who had all false
        patients_union = set(df.loc[df[preop_cols].eq(False).all(axis=1), 'SubjectId'])

        baseline_count = len(patients_union)

        # Get corresponding post-op column names from neuro_sign_map
        postop_cols = [preop_to_refined_neuro_map[s] for s in sub_symptoms]

        # Get the actual data
        subset = df[df['SubjectId'].isin(patients_union)][['SubjectId'] + postop_cols].fillna(0)

        # Use max value across post-op indicators
        subset['Outcome'] = subset[postop_cols].max(axis=1)
        subset['Symptom'] = new_symptom
        print(subset)
        print(subset.columns)
        # Count distinct subjects per outcome category
        count_df = subset.groupby('Outcome')['SubjectId'].nunique().reset_index()

        count_df['Symptom'] = new_symptom
        count_df = count_df.rename(columns={'SubjectId': 'N_Patients'})
        count_pivot = count_df.pivot(index='Symptom', columns='Outcome', values='N_Patients').fillna(0)
        count_pivot['NotPresentBaseline'] = baseline_count

        all_summaries.append(count_pivot)

    outcome_labels = {
        1: 'Resolved',
        2: 'Improved',
        3: 'Stable',
        4: 'Worse',
        0: 'Unknown',
        'Nan in the datasheets':'Nan in the datasheets',
        '2': 'Improved',
        '0':'Unknown',
        '1':'Resolved',
        '3':'Stable',
        '4':'Worse'
    }

    # 5. Reorder columns (only include if present)
    desired_order = [
        'NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse',
        'Unknown','Nan in the datasheets'
    ]

    # Combine and rename
    summary_df = pd.concat(all_summaries).fillna(0)

#     summary_df = summary_df.replace({
#     '1': 1,
#     '2': 2,
#     '3': 3,
#         '4':4,
#         '0':0
# })
    summary_df = summary_df.rename(columns=outcome_labels)

    # Reorder
    summary_df = summary_df[[col for col in desired_order if col in summary_df.columns]]
    summary_df = summary_df.reset_index()
    summary_df['Group'] = label

    return summary_df,subset


# Apply separately to each group
pfd_summary,pfd_subset = summarize_symptoms(pfd_df, label='PFD')
print('======================================================split betwwen pfd and pfdd============================================================================================')
pfdd_summary,pfdd_subset = summarize_symptoms(pfdd_df, label='PFDD')


pfd_summary

Preop_Papilledema
Preop_Nystagmus
Preop_DisconjugateGaze
Preop_ExtraocularPalsies
Preop_FacialWeakness
Preop_DisturbanceInFacialSensation
Preop_HearingLoss
Preop_Hoarseness_x
Preop_TongueDeviation
Preop_WeakShrug
Preop_LeftUpperExtremityWeak
Preop_RightUpperExtremityWeak
Preop_LeftLowerExtremityWeak
Preop_RightLowerExtremityWeak
Preop_LighttouchEntireBody
Preop_DLTLeftUpperExtremities
Preop_DLTRightUpperExtremities
Preop_DLTLeftLowerExtremities
Preop_DLTRightLowerExtremities
Preop_DeficitToPinprickUpperLeft
Preop_DeficitToPinprickUpperRight
Preop_DeficittoPinprickLowerLeft
Preop_DeficittoPinprickLowerRight
Preop_LightTouchTorso
Preop_LightTouchSaddle
Preop_DeepTendonReflexes
Preop_AnkleClonus
Preop_GaitInstability
     SubjectId  Refined_LeftUpperExtremityStrength  \
0            1                                 3.0
1            2                                 3.0
4            5                                 3.0
5            6                                 3.0
6            7                                 3.0
..         ...                                 ...
152        159                                 3.0
155        162                                 3.0
157        164                                 3.0
159        166                                 3.0
160        167                                 3.0

     Refined_RightUpperExtremityStrength  Outcome  \
0                                    3.0      3.0
1                                    3.0      3.0
4                                    3.0      3.0
5                                    3.0      3.0
6                                    3.0      3.0
..                                   ...      ...
152                                  3.0      3.0
155                                  3.0      3.0
157                                  3.0      3.0
159                                  3.0      3.0
160                                  3.0      3.0

                              Symptom
0    Preop_CombinedUpperExtremityWeak
1    Preop_CombinedUpperExtremityWeak
4    Preop_CombinedUpperExtremityWeak
5    Preop_CombinedUpperExtremityWeak
6    Preop_CombinedUpperExtremityWeak
..                                ...
152  Preop_CombinedUpperExtremityWeak
155  Preop_CombinedUpperExtremityWeak
157  Preop_CombinedUpperExtremityWeak
159  Preop_CombinedUpperExtremityWeak
160  Preop_CombinedUpperExtremityWeak

[82 rows x 5 columns]
Index(['SubjectId', 'Refined_LeftUpperExtremityStrength',
       'Refined_RightUpperExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
     SubjectId  Refined_LeftLowerExtremityStrength  \
0            1                                 3.0
1            2                                 3.0
4            5                                 3.0
5            6                                 3.0
6            7                                 3.0
..         ...                                 ...
152        159                                 3.0
155        162                                 3.0
157        164                                 3.0
159        166                                 3.0
160        167                                 3.0

     Refined_RightLowerExtremityStrength  Outcome  \
0                                    3.0      3.0
1                                    3.0      3.0
4                                    3.0      3.0
5                                    3.0      3.0
6                                    3.0      3.0
..                                   ...      ...
152                                  3.0      3.0
155                                  3.0      3.0
157                                  3.0      3.0
159                                  3.0      3.0
160                                  3.0      3.0

                              Symptom
0    Preop_CombinedLowerExtremityWeak
1    Preop_CombinedLowerExtremityWeak
4    Preop_CombinedLowerExtremityWeak
5    Preop_CombinedLowerExtremityWeak
6    Preop_CombinedLowerExtremityWeak
..                                ...
152  Preop_CombinedLowerExtremityWeak
155  Preop_CombinedLowerExtremityWeak
157  Preop_CombinedLowerExtremityWeak
159  Preop_CombinedLowerExtremityWeak
160  Preop_CombinedLowerExtremityWeak

[84 rows x 5 columns]
Index(['SubjectId', 'Refined_LeftLowerExtremityStrength',
       'Refined_RightLowerExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
     SubjectId  Refined_LightTouchSensoryDeficitLUE  \
0            1                                  3.0
1            2                                  3.0
4            5                                  3.0
5            6                                  3.0
6            7                                  3.0
..         ...                                  ...
152        159                                  3.0
155        162                                  3.0
157        164                                  3.0
159        166                                  3.0
160        167                                  3.0

     Refined_LightTouchSensoryDeficitRUE  Outcome  \
0                                    3.0      3.0
1                                    3.0      3.0
4                                    3.0      3.0
5                                    3.0      3.0
6                                    3.0      3.0
..                                   ...      ...
152                                  3.0      3.0
155                                  3.0      3.0
157                                  3.0      3.0
159                                  3.0      3.0
160                                  3.0      3.0

                             Symptom
0    Preop_CombinedUpperDLTExtremity
1    Preop_CombinedUpperDLTExtremity
4    Preop_CombinedUpperDLTExtremity
5    Preop_CombinedUpperDLTExtremity
6    Preop_CombinedUpperDLTExtremity
..                               ...
152  Preop_CombinedUpperDLTExtremity
155  Preop_CombinedUpperDLTExtremity
157  Preop_CombinedUpperDLTExtremity
159  Preop_CombinedUpperDLTExtremity
160  Preop_CombinedUpperDLTExtremity

[82 rows x 5 columns]
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLUE',
       'Refined_LightTouchSensoryDeficitRUE', 'Outcome', 'Symptom'],
      dtype='object')
     SubjectId  Refined_LightTouchSensoryDeficitLLE  \
0            1                                  3.0
1            2                                  3.0
4            5                                  3.0
5            6                                  3.0
6            7                                  3.0
..         ...                                  ...
152        159                                  3.0
155        162                                  3.0
157        164                                  3.0
159        166                                  3.0
160        167                                  3.0

     Refined_LightTouchSensoryDeficitRLE  Outcome  \
0                                    3.0      3.0
1                                    3.0      3.0
4                                    3.0      3.0
5                                    3.0      3.0
6                                    3.0      3.0
..                                   ...      ...
152                                  3.0      3.0
155                                  3.0      3.0
157                                  3.0      3.0
159                                  3.0      3.0
160                                  3.0      3.0

                             Symptom
0    Preop_CombinedLowerDLTExtremity
1    Preop_CombinedLowerDLTExtremity
4    Preop_CombinedLowerDLTExtremity
5    Preop_CombinedLowerDLTExtremity
6    Preop_CombinedLowerDLTExtremity
..                               ...
152  Preop_CombinedLowerDLTExtremity
155  Preop_CombinedLowerDLTExtremity
157  Preop_CombinedLowerDLTExtremity
159  Preop_CombinedLowerDLTExtremity
160  Preop_CombinedLowerDLTExtremity

[84 rows x 5 columns]
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLLE',
       'Refined_LightTouchSensoryDeficitRLE', 'Outcome', 'Symptom'],
      dtype='object')
======================================================split betwwen pfd and pfdd============================================================================================
Preop_Papilledema
Preop_Nystagmus
Preop_DisconjugateGaze
Preop_ExtraocularPalsies
Preop_FacialWeakness
Preop_DisturbanceInFacialSensation
Preop_HearingLoss
Preop_Hoarseness_x
Preop_TongueDeviation
Preop_WeakShrug
Preop_LeftUpperExtremityWeak
Preop_RightUpperExtremityWeak
Preop_LeftLowerExtremityWeak
Preop_RightLowerExtremityWeak
Preop_LighttouchEntireBody
Preop_DLTLeftUpperExtremities
Preop_DLTRightUpperExtremities
Preop_DLTLeftLowerExtremities
Preop_DLTRightLowerExtremities
Preop_DeficitToPinprickUpperLeft
Preop_DeficitToPinprickUpperRight
Preop_DeficittoPinprickLowerLeft
Preop_DeficittoPinprickLowerRight
Preop_LightTouchTorso
Preop_LightTouchSaddle
Preop_DeepTendonReflexes
Preop_AnkleClonus
Preop_GaitInstability
     SubjectId  Refined_LeftUpperExtremityStrength  \
2            3                                 3.0
3            4                                 3.0
8            9                                 3.0
10          11                                 3.0
13          15                                 3.0
..         ...                                 ...
153        160                                 3.0
154        161                                 3.0
156        163                                 3.0
158        165                                 3.0
161        168                                 3.0

     Refined_RightUpperExtremityStrength  Outcome  \
2                                    3.0      3.0
3                                    3.0      3.0
8                                    3.0      3.0
10                                   3.0      3.0
13                                   3.0      3.0
..                                   ...      ...
153                                  3.0      3.0
154                                  3.0      3.0
156                                  3.0      3.0
158                                  3.0      3.0
161                                  3.0      3.0

                              Symptom
2    Preop_CombinedUpperExtremityWeak
3    Preop_CombinedUpperExtremityWeak
8    Preop_CombinedUpperExtremityWeak
10   Preop_CombinedUpperExtremityWeak
13   Preop_CombinedUpperExtremityWeak
..                                ...
153  Preop_CombinedUpperExtremityWeak
154  Preop_CombinedUpperExtremityWeak
156  Preop_CombinedUpperExtremityWeak
158  Preop_CombinedUpperExtremityWeak
161  Preop_CombinedUpperExtremityWeak

[76 rows x 5 columns]
Index(['SubjectId', 'Refined_LeftUpperExtremityStrength',
       'Refined_RightUpperExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
     SubjectId  Refined_LeftLowerExtremityStrength  \
2            3                                 3.0
3            4                                 3.0
8            9                                 3.0
10          11                                 3.0
13          15                                 3.0
..         ...                                 ...
153        160                                 3.0
154        161                                 3.0
156        163                                 3.0
158        165                                 3.0
161        168                                 3.0

     Refined_RightLowerExtremityStrength  Outcome  \
2                                    3.0      3.0
3                                    3.0      3.0
8                                    3.0      3.0
10                                   3.0      3.0
13                                   3.0      3.0
..                                   ...      ...
153                                  3.0      3.0
154                                  3.0      3.0
156                                  3.0      3.0
158                                  3.0      3.0
161                                  3.0      3.0

                              Symptom
2    Preop_CombinedLowerExtremityWeak
3    Preop_CombinedLowerExtremityWeak
8    Preop_CombinedLowerExtremityWeak
10   Preop_CombinedLowerExtremityWeak
13   Preop_CombinedLowerExtremityWeak
..                                ...
153  Preop_CombinedLowerExtremityWeak
154  Preop_CombinedLowerExtremityWeak
156  Preop_CombinedLowerExtremityWeak
158  Preop_CombinedLowerExtremityWeak
161  Preop_CombinedLowerExtremityWeak

[78 rows x 5 columns]
Index(['SubjectId', 'Refined_LeftLowerExtremityStrength',
       'Refined_RightLowerExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
     SubjectId  Refined_LightTouchSensoryDeficitLUE  \
2            3                                  3.0
3            4                                  3.0
8            9                                  3.0
10          11                                  3.0
13          15                                  3.0
..         ...                                  ...
153        160                                  3.0
154        161                                  3.0
156        163                                  3.0
158        165                                  3.0
161        168                                  3.0

     Refined_LightTouchSensoryDeficitRUE  Outcome  \
2                                    3.0      3.0
3                                    3.0      3.0
8                                    3.0      3.0
10                                   3.0      3.0
13                                   3.0      3.0
..                                   ...      ...
153                                  3.0      3.0
154                                  3.0      3.0
156                                  3.0      3.0
158                                  3.0      3.0
161                                  3.0      3.0

                             Symptom
2    Preop_CombinedUpperDLTExtremity
3    Preop_CombinedUpperDLTExtremity
8    Preop_CombinedUpperDLTExtremity
10   Preop_CombinedUpperDLTExtremity
13   Preop_CombinedUpperDLTExtremity
..                               ...
153  Preop_CombinedUpperDLTExtremity
154  Preop_CombinedUpperDLTExtremity
156  Preop_CombinedUpperDLTExtremity
158  Preop_CombinedUpperDLTExtremity
161  Preop_CombinedUpperDLTExtremity

[75 rows x 5 columns]
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLUE',
       'Refined_LightTouchSensoryDeficitRUE', 'Outcome', 'Symptom'],
      dtype='object')
     SubjectId  Refined_LightTouchSensoryDeficitLLE  \
2            3                                  3.0
3            4                                  3.0
8            9                                  3.0
10          11                                  3.0
13          15                                  3.0
..         ...                                  ...
153        160                                  3.0
154        161                                  3.0
156        163                                  3.0
158        165                                  3.0
161        168                                  3.0

     Refined_LightTouchSensoryDeficitRLE  Outcome  \
2                                    3.0      3.0
3                                    3.0      3.0
8                                    3.0      3.0
10                                   3.0      3.0
13                                   3.0      3.0
..                                   ...      ...
153                                  3.0      3.0
154                                  3.0      3.0
156                                  3.0      3.0
158                                  3.0      3.0
161                                  3.0      3.0

                             Symptom
2    Preop_CombinedLowerDLTExtremity
3    Preop_CombinedLowerDLTExtremity
8    Preop_CombinedLowerDLTExtremity
10   Preop_CombinedLowerDLTExtremity
13   Preop_CombinedLowerDLTExtremity
..                               ...
153  Preop_CombinedLowerDLTExtremity
154  Preop_CombinedLowerDLTExtremity
156  Preop_CombinedLowerDLTExtremity
158  Preop_CombinedLowerDLTExtremity
161  Preop_CombinedLowerDLTExtremity

[78 rows x 5 columns]
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLLE',
       'Refined_LightTouchSensoryDeficitRLE', 'Outcome', 'Symptom'],
      dtype='object')

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group
0,Preop_Papilledema,83,83,0.0,PFD
1,Preop_Nystagmus,80,80,0.0,PFD
2,Preop_DisconjugateGaze,83,82,1.0,PFD
3,Preop_ExtraocularPalsies,82,82,0.0,PFD
4,Preop_FacialWeakness,84,84,0.0,PFD
5,Preop_DisturbanceInFacialSensation,83,83,0.0,PFD
6,Preop_HearingLoss,83,83,0.0,PFD
7,Preop_Hoarseness_x,82,82,0.0,PFD
8,Preop_TongueDeviation,84,84,0.0,PFD
9,Preop_WeakShrug,84,84,0.0,PFD
10,Preop_LeftUpperExtremityWeak,83,83,0.0,PFD
11,Preop_RightUpperExtremityWeak,83,83,0.0,PFD
12,Preop_LeftLowerExtremityWeak,84,83,1.0,PFD
13,Preop_RightLowerExtremityWeak,84,84,0.0,PFD
14,Preop_LighttouchEntireBody,84,84,0.0,PFD
15,Preop_DLTLeftUpperExtremities,83,83,0.0,PFD
16,Preop_DLTRightUpperExtremities,83,82,1.0,PFD
17,Preop_DLTLeftLowerExtremities,84,84,0.0,PFD
18,Preop_DLTRightLowerExtremities,84,84,0.0,PFD
19,Preop_DeficitToPinprickUpperLeft,84,84,0.0,PFD
20,Preop_DeficitToPinprickUpperRight,84,83,1.0,PFD
21,Preop_DeficittoPinprickLowerLeft,84,84,0.0,PFD
22,Preop_DeficittoPinprickLowerRight,84,84,0.0,PFD
23,Preop_LightTouchTorso,84,84,0.0,PFD
24,Preop_LightTouchSaddle,84,84,0.0,PFD
25,Preop_DeepTendonReflexes,83,82,1.0,PFD
26,Preop_AnkleClonus,82,81,1.0,PFD
27,Preop_GaitInstability,80,80,0.0,PFD
28,Preop_CombinedUpperExtremityWeak,82,82,0.0,PFD
29,Preop_CombinedLowerExtremityWeak,84,83,1.0,PFD
30,Preop_CombinedUpperDLTExtremity,82,81,1.0,PFD
31,Preop_CombinedLowerDLTExtremity,84,84,0.0,PFD

In [21]:
pfd_df[pfd_df['Refined_Nystagmus']==1]

,SubjectId,Preop_Papilledema,Index_Papilledema,Limonadi_Index_Papilledema,Refined_Papilledema,Limonadi_Papilledema,Preop_Nystagmus,Index_Nystagmus,Limonadi_Index_Nystagmus,Refined_Nystagmus,...,Refined_IncontinenceSymptoms,Limonadi_IncontinenceSymptoms,Preop_SexualDysfunction,IndexSexualDysfunctionSymptoms,Limonadi_Index_SexualDysfunctionSymptoms,Overall_SexualDysfunctionSymp,Limonadi_Overall_SexualDysfunctionSymp,Refined_SexualDysfunctionSymptoms,Limonadi_SexualDysfunctionSymptoms,none_preop
119,122,0,3.0,0.0,3,0,1,1.0,2.0,1.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
133,136,0,3.0,0.0,3,0,1,1.0,2.0,1.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0

In [22]:
pfdd_subset

,SubjectId,Refined_LightTouchSensoryDeficitLLE,Refined_LightTouchSensoryDeficitRLE,Outcome,Symptom
2,3,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
3,4,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
8,9,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
10,11,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
13,15,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
...,...,...,...,...,...
153,160,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
154,161,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
156,163,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
158,165,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity
161,168,3.0,3.0,3.0,Preop_CombinedLowerDLTExtremity

In [23]:
list(pfd_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [24]:
pfd_summary

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group
0,Preop_Papilledema,83,83,0.0,PFD
1,Preop_Nystagmus,80,80,0.0,PFD
2,Preop_DisconjugateGaze,83,82,1.0,PFD
3,Preop_ExtraocularPalsies,82,82,0.0,PFD
4,Preop_FacialWeakness,84,84,0.0,PFD
5,Preop_DisturbanceInFacialSensation,83,83,0.0,PFD
6,Preop_HearingLoss,83,83,0.0,PFD
7,Preop_Hoarseness_x,82,82,0.0,PFD
8,Preop_TongueDeviation,84,84,0.0,PFD
9,Preop_WeakShrug,84,84,0.0,PFD
10,Preop_LeftUpperExtremityWeak,83,83,0.0,PFD
11,Preop_RightUpperExtremityWeak,83,83,0.0,PFD
12,Preop_LeftLowerExtremityWeak,84,83,1.0,PFD
13,Preop_RightLowerExtremityWeak,84,84,0.0,PFD
14,Preop_LighttouchEntireBody,84,84,0.0,PFD
15,Preop_DLTLeftUpperExtremities,83,83,0.0,PFD
16,Preop_DLTRightUpperExtremities,83,82,1.0,PFD
17,Preop_DLTLeftLowerExtremities,84,84,0.0,PFD
18,Preop_DLTRightLowerExtremities,84,84,0.0,PFD
19,Preop_DeficitToPinprickUpperLeft,84,84,0.0,PFD
20,Preop_DeficitToPinprickUpperRight,84,83,1.0,PFD
21,Preop_DeficittoPinprickLowerLeft,84,84,0.0,PFD
22,Preop_DeficittoPinprickLowerRight,84,84,0.0,PFD
23,Preop_LightTouchTorso,84,84,0.0,PFD
24,Preop_LightTouchSaddle,84,84,0.0,PFD
25,Preop_DeepTendonReflexes,83,82,1.0,PFD
26,Preop_AnkleClonus,82,81,1.0,PFD
27,Preop_GaitInstability,80,80,0.0,PFD
28,Preop_CombinedUpperExtremityWeak,82,82,0.0,PFD
29,Preop_CombinedLowerExtremityWeak,84,83,1.0,PFD
30,Preop_CombinedUpperDLTExtremity,82,81,1.0,PFD
31,Preop_CombinedLowerDLTExtremity,84,84,0.0,PFD

In [25]:
pfd_summary

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group
0,Preop_Papilledema,83,83,0.0,PFD
1,Preop_Nystagmus,80,80,0.0,PFD
2,Preop_DisconjugateGaze,83,82,1.0,PFD
3,Preop_ExtraocularPalsies,82,82,0.0,PFD
4,Preop_FacialWeakness,84,84,0.0,PFD
5,Preop_DisturbanceInFacialSensation,83,83,0.0,PFD
6,Preop_HearingLoss,83,83,0.0,PFD
7,Preop_Hoarseness_x,82,82,0.0,PFD
8,Preop_TongueDeviation,84,84,0.0,PFD
9,Preop_WeakShrug,84,84,0.0,PFD
10,Preop_LeftUpperExtremityWeak,83,83,0.0,PFD
11,Preop_RightUpperExtremityWeak,83,83,0.0,PFD
12,Preop_LeftLowerExtremityWeak,84,83,1.0,PFD
13,Preop_RightLowerExtremityWeak,84,84,0.0,PFD
14,Preop_LighttouchEntireBody,84,84,0.0,PFD
15,Preop_DLTLeftUpperExtremities,83,83,0.0,PFD
16,Preop_DLTRightUpperExtremities,83,82,1.0,PFD
17,Preop_DLTLeftLowerExtremities,84,84,0.0,PFD
18,Preop_DLTRightLowerExtremities,84,84,0.0,PFD
19,Preop_DeficitToPinprickUpperLeft,84,84,0.0,PFD
20,Preop_DeficitToPinprickUpperRight,84,83,1.0,PFD
21,Preop_DeficittoPinprickLowerLeft,84,84,0.0,PFD
22,Preop_DeficittoPinprickLowerRight,84,84,0.0,PFD
23,Preop_LightTouchTorso,84,84,0.0,PFD
24,Preop_LightTouchSaddle,84,84,0.0,PFD
25,Preop_DeepTendonReflexes,83,82,1.0,PFD
26,Preop_AnkleClonus,82,81,1.0,PFD
27,Preop_GaitInstability,80,80,0.0,PFD
28,Preop_CombinedUpperExtremityWeak,82,82,0.0,PFD
29,Preop_CombinedLowerExtremityWeak,84,83,1.0,PFD
30,Preop_CombinedUpperDLTExtremity,82,81,1.0,PFD
31,Preop_CombinedLowerDLTExtremity,84,84,0.0,PFD

In [26]:
# Define all outcome-related columns to sum
outcome_cols = [
    'Resolved',
    'Improved',
    'Stable',
    'Worse',
    'Unknown',
# 'Nan in the datasheets'
#     'Nan in the datasheets'
]

for col in outcome_cols:
    if col not in pfd_summary.columns:
        pfd_summary[col] = 0.0

# Check for mismatches in PFD
pfd_summary['TotalCounted'] = pfd_summary[outcome_cols].sum(axis=1)
pfd_summary['equal'] = pfd_summary['TotalCounted'] == pfd_summary['NotPresentBaseline'] 
pfd_summary

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group,Resolved,Improved,Unknown,TotalCounted,equal
0,Preop_Papilledema,83,83,0.0,PFD,0.0,0.0,0.0,83.0,True
1,Preop_Nystagmus,80,80,0.0,PFD,0.0,0.0,0.0,80.0,True
2,Preop_DisconjugateGaze,83,82,1.0,PFD,0.0,0.0,0.0,83.0,True
3,Preop_ExtraocularPalsies,82,82,0.0,PFD,0.0,0.0,0.0,82.0,True
4,Preop_FacialWeakness,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
5,Preop_DisturbanceInFacialSensation,83,83,0.0,PFD,0.0,0.0,0.0,83.0,True
6,Preop_HearingLoss,83,83,0.0,PFD,0.0,0.0,0.0,83.0,True
7,Preop_Hoarseness_x,82,82,0.0,PFD,0.0,0.0,0.0,82.0,True
8,Preop_TongueDeviation,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
9,Preop_WeakShrug,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
10,Preop_LeftUpperExtremityWeak,83,83,0.0,PFD,0.0,0.0,0.0,83.0,True
11,Preop_RightUpperExtremityWeak,83,83,0.0,PFD,0.0,0.0,0.0,83.0,True
12,Preop_LeftLowerExtremityWeak,84,83,1.0,PFD,0.0,0.0,0.0,84.0,True
13,Preop_RightLowerExtremityWeak,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
14,Preop_LighttouchEntireBody,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
15,Preop_DLTLeftUpperExtremities,83,83,0.0,PFD,0.0,0.0,0.0,83.0,True
16,Preop_DLTRightUpperExtremities,83,82,1.0,PFD,0.0,0.0,0.0,83.0,True
17,Preop_DLTLeftLowerExtremities,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
18,Preop_DLTRightLowerExtremities,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
19,Preop_DeficitToPinprickUpperLeft,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
20,Preop_DeficitToPinprickUpperRight,84,83,1.0,PFD,0.0,0.0,0.0,84.0,True
21,Preop_DeficittoPinprickLowerLeft,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
22,Preop_DeficittoPinprickLowerRight,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
23,Preop_LightTouchTorso,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
24,Preop_LightTouchSaddle,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True
25,Preop_DeepTendonReflexes,83,82,1.0,PFD,0.0,0.0,0.0,83.0,True
26,Preop_AnkleClonus,82,81,1.0,PFD,0.0,0.0,0.0,82.0,True
27,Preop_GaitInstability,80,80,0.0,PFD,0.0,0.0,0.0,80.0,True
28,Preop_CombinedUpperExtremityWeak,82,82,0.0,PFD,0.0,0.0,0.0,82.0,True
29,Preop_CombinedLowerExtremityWeak,84,83,1.0,PFD,0.0,0.0,0.0,84.0,True
30,Preop_CombinedUpperDLTExtremity,82,81,1.0,PFD,0.0,0.0,0.0,82.0,True
31,Preop_CombinedLowerDLTExtremity,84,84,0.0,PFD,0.0,0.0,0.0,84.0,True

In [27]:
combo_groups = {
    'Preop_CombinedUpperExtremityWeak': ['Preop_LeftUpperExtremityWeak', 'Preop_RightUpperExtremityWeak'],
    'Preop_CombinedLowerExtremityWeak': ['Preop_LeftLowerExtremityWeak', 'Preop_RightLowerExtremityWeak'],
    'Preop_CombinedUpperDLTExtremity': ['Preop_DLTLeftUpperExtremities', 'Preop_DLTRightUpperExtremities'],
    'Preop_CombinedLowerDLTExtremity': ['Preop_DLTLeftLowerExtremities', 'Preop_DLTRightLowerExtremities'],
}
desired_order = list(preop_to_refined_neuro_map.keys())+list(combo_groups.keys())

# Ensure all needed columns exist
required_columns = ['Symptom', 'NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'Group', 'TotalCounted', 'equal']
for col in required_columns:
    if col not in pfd_summary.columns:
        pfd_summary[col] = 0

# Set index to 'Symptom' for easy reindexing
pfd_summary.set_index('Symptom', inplace=True)

# Reindex with desired order and fill all missing values with NaN (temporarily)
pfd_summary_ordered = pfd_summary.reindex(desired_order).reset_index()

# Fill missing values in specific columns first
pfd_summary_ordered['Group'] = pfd_summary_ordered['Group'].fillna('PFD')
pfd_summary_ordered['equal'] = pfd_summary_ordered['equal'].fillna(True)

# Fill remaining numeric columns with 0
pfd_summary_ordered.fillna(0, inplace=True)



# Convert appropriate columns to integers (if needed)
int_cols = ['NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'TotalCounted']
pfd_summary_ordered[int_cols] = pfd_summary_ordered[int_cols].astype(int)

In [28]:
desired_order = [
    'Papilledema', 'Nystagmus', 'DisconjugateGaze', 'ExtraocularPalsies',
    'FacialWeakness', 'DisturbanceInFacialSensation', 'HearingLoss',
    'Hoarseness_x', 'TongueDeviation', 'WeakShrug',

    'CombinedUpperExtremityWeak', 'LeftUpperExtremityWeak', 'RightUpperExtremityWeak',
    'CombinedLowerExtremityWeak', 'LeftLowerExtremityWeak', 'RightLowerExtremityWeak',

    'LighttouchEntireBody',
    'CombinedUpperDLTExtremity', 'DLTLeftUpperExtremities', 'DLTRightUpperExtremities',
    'CombinedLowerDLTExtremity', 'DLTLeftLowerExtremities', 'DLTRightLowerExtremities',

    'DeficitToPinprickUpperLeft', 'DeficitToPinprickUpperRight',
    'DeficittoPinprickLowerLeft', 'DeficittoPinprickLowerRight',
    'LightTouchTorso', 'LightTouchSaddle',
    'DeepTendonReflexes', 'AnkleClonus', 'GaitInstability'
]
desired_order = ['Preop_'+s for s in desired_order]
# Create a mapping from symptom to its desired sort order
order_map = {symptom: i for i, symptom in enumerate(desired_order)}


# Add a sort index column
pfd_summary_ordered['sort_order'] = pfd_summary_ordered['Symptom'].map(order_map)

# Sort and clean up
pfd_summary_ordered = pfd_summary_ordered.sort_values(by='sort_order').drop(columns='sort_order').reset_index(drop=True)

In [29]:
pfd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group,Resolved,Improved,Unknown,TotalCounted,equal
0,Preop_Papilledema,83,83,0,PFD,0,0,0,83,True
1,Preop_Nystagmus,80,80,0,PFD,0,0,0,80,True
2,Preop_DisconjugateGaze,83,82,1,PFD,0,0,0,83,True
3,Preop_ExtraocularPalsies,82,82,0,PFD,0,0,0,82,True
4,Preop_FacialWeakness,84,84,0,PFD,0,0,0,84,True
5,Preop_DisturbanceInFacialSensation,83,83,0,PFD,0,0,0,83,True
6,Preop_HearingLoss,83,83,0,PFD,0,0,0,83,True
7,Preop_Hoarseness_x,82,82,0,PFD,0,0,0,82,True
8,Preop_TongueDeviation,84,84,0,PFD,0,0,0,84,True
9,Preop_WeakShrug,84,84,0,PFD,0,0,0,84,True
10,Preop_CombinedUpperExtremityWeak,82,82,0,PFD,0,0,0,82,True
11,Preop_LeftUpperExtremityWeak,83,83,0,PFD,0,0,0,83,True
12,Preop_RightUpperExtremityWeak,83,83,0,PFD,0,0,0,83,True
13,Preop_CombinedLowerExtremityWeak,84,83,1,PFD,0,0,0,84,True
14,Preop_LeftLowerExtremityWeak,84,83,1,PFD,0,0,0,84,True
15,Preop_RightLowerExtremityWeak,84,84,0,PFD,0,0,0,84,True
16,Preop_LighttouchEntireBody,84,84,0,PFD,0,0,0,84,True
17,Preop_CombinedUpperDLTExtremity,82,81,1,PFD,0,0,0,82,True
18,Preop_DLTLeftUpperExtremities,83,83,0,PFD,0,0,0,83,True
19,Preop_DLTRightUpperExtremities,83,82,1,PFD,0,0,0,83,True
20,Preop_CombinedLowerDLTExtremity,84,84,0,PFD,0,0,0,84,True
21,Preop_DLTLeftLowerExtremities,84,84,0,PFD,0,0,0,84,True
22,Preop_DLTRightLowerExtremities,84,84,0,PFD,0,0,0,84,True
23,Preop_DeficitToPinprickUpperLeft,84,84,0,PFD,0,0,0,84,True
24,Preop_DeficitToPinprickUpperRight,84,83,1,PFD,0,0,0,84,True
25,Preop_DeficittoPinprickLowerLeft,84,84,0,PFD,0,0,0,84,True
26,Preop_DeficittoPinprickLowerRight,84,84,0,PFD,0,0,0,84,True
27,Preop_LightTouchTorso,84,84,0,PFD,0,0,0,84,True
28,Preop_LightTouchSaddle,84,84,0,PFD,0,0,0,84,True
29,Preop_DeepTendonReflexes,83,82,1,PFD,0,0,0,83,True
30,Preop_AnkleClonus,82,81,1,PFD,0,0,0,82,True
31,Preop_GaitInstability,80,80,0,PFD,0,0,0,80,True

In [30]:

required_columns = ['Symptom', 'NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'Group', 'TotalCounted', 'equal']
for col in required_columns:
    if col not in pfdd_summary.columns:
        pfdd_summary[col] = 0

# Set index to 'Symptom' for easy reindexing
pfdd_summary.set_index('Symptom', inplace=True)

# Reindex with desired order and fill all missing values with NaN (temporarily)
pfdd_summary_ordered = pfdd_summary.reindex(desired_order).reset_index()

# Fill missing values in specific columns first
pfdd_summary_ordered['Group'] = pfdd_summary_ordered['Group'].fillna('PFDD')
pfdd_summary_ordered['equal'] = pfdd_summary_ordered['equal'].fillna(True)

# Fill remaining numeric columns with 0
pfdd_summary_ordered.fillna(0, inplace=True)



# Convert appropriate columns to integers (if needed)
int_cols = ['NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'TotalCounted']
pfdd_summary_ordered[int_cols] = pfdd_summary_ordered[int_cols].astype(int)

In [31]:
# Define all outcome-related columns to sum
outcome_cols = [
    'Resolved',
    'Improved',
    'Stable',
    'Worse',
    'Unknown',
# 'Nan in the datasheets'
#     'Nan in the datasheets'
]

# Check for mismatches in PFDD
pfdd_summary['TotalCounted'] = pfdd_summary[outcome_cols].sum(axis=1)
pfdd_summary['equal'] = pfdd_summary['TotalCounted'] == pfdd_summary['NotPresentBaseline']

In [32]:
pfdd_summary

Outcome,NotPresentBaseline,Stable,Worse,Group,Resolved,Improved,Unknown,TotalCounted,equal
Symptom,,,,,,,,,
Preop_Papilledema,77,77,0.0,PFDD,0,0,0,77.0,True
Preop_Nystagmus,73,73,0.0,PFDD,0,0,0,73.0,True
Preop_DisconjugateGaze,77,77,0.0,PFDD,0,0,0,77.0,True
Preop_ExtraocularPalsies,76,76,0.0,PFDD,0,0,0,76.0,True
Preop_FacialWeakness,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DisturbanceInFacialSensation,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_HearingLoss,77,77,0.0,PFDD,0,0,0,77.0,True
Preop_Hoarseness_x,77,77,0.0,PFDD,0,0,0,77.0,True
Preop_TongueDeviation,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_WeakShrug,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_LeftUpperExtremityWeak,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_RightUpperExtremityWeak,76,76,0.0,PFDD,0,0,0,76.0,True
Preop_LeftLowerExtremityWeak,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_RightLowerExtremityWeak,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_LighttouchEntireBody,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DLTLeftUpperExtremities,76,76,0.0,PFDD,0,0,0,76.0,True
Preop_DLTRightUpperExtremities,76,76,0.0,PFDD,0,0,0,76.0,True
Preop_DLTLeftLowerExtremities,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DLTRightLowerExtremities,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DeficitToPinprickUpperLeft,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DeficitToPinprickUpperRight,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DeficittoPinprickLowerLeft,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DeficittoPinprickLowerRight,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_LightTouchTorso,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_LightTouchSaddle,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_DeepTendonReflexes,71,69,2.0,PFDD,0,0,0,71.0,True
Preop_AnkleClonus,77,77,0.0,PFDD,0,0,0,77.0,True
Preop_GaitInstability,69,68,1.0,PFDD,0,0,0,69.0,True
Preop_CombinedUpperExtremityWeak,76,76,0.0,PFDD,0,0,0,76.0,True
Preop_CombinedLowerExtremityWeak,78,78,0.0,PFDD,0,0,0,78.0,True
Preop_CombinedUpperDLTExtremity,75,75,0.0,PFDD,0,0,0,75.0,True
Preop_CombinedLowerDLTExtremity,78,78,0.0,PFDD,0,0,0,78.0,True

In [33]:
# Add a sort index column
pfd_summary_ordered['sort_order'] = pfd_summary_ordered['Symptom'].map(order_map)

# Sort and clean up
pfd_summary_ordered = pfd_summary_ordered.sort_values(by='sort_order').drop(columns='sort_order').reset_index(drop=True)

In [34]:
pfd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group,Resolved,Improved,Unknown,TotalCounted,equal
0,Preop_Papilledema,83,83,0,PFD,0,0,0,83,True
1,Preop_Nystagmus,80,80,0,PFD,0,0,0,80,True
2,Preop_DisconjugateGaze,83,82,1,PFD,0,0,0,83,True
3,Preop_ExtraocularPalsies,82,82,0,PFD,0,0,0,82,True
4,Preop_FacialWeakness,84,84,0,PFD,0,0,0,84,True
5,Preop_DisturbanceInFacialSensation,83,83,0,PFD,0,0,0,83,True
6,Preop_HearingLoss,83,83,0,PFD,0,0,0,83,True
7,Preop_Hoarseness_x,82,82,0,PFD,0,0,0,82,True
8,Preop_TongueDeviation,84,84,0,PFD,0,0,0,84,True
9,Preop_WeakShrug,84,84,0,PFD,0,0,0,84,True
10,Preop_CombinedUpperExtremityWeak,82,82,0,PFD,0,0,0,82,True
11,Preop_LeftUpperExtremityWeak,83,83,0,PFD,0,0,0,83,True
12,Preop_RightUpperExtremityWeak,83,83,0,PFD,0,0,0,83,True
13,Preop_CombinedLowerExtremityWeak,84,83,1,PFD,0,0,0,84,True
14,Preop_LeftLowerExtremityWeak,84,83,1,PFD,0,0,0,84,True
15,Preop_RightLowerExtremityWeak,84,84,0,PFD,0,0,0,84,True
16,Preop_LighttouchEntireBody,84,84,0,PFD,0,0,0,84,True
17,Preop_CombinedUpperDLTExtremity,82,81,1,PFD,0,0,0,82,True
18,Preop_DLTLeftUpperExtremities,83,83,0,PFD,0,0,0,83,True
19,Preop_DLTRightUpperExtremities,83,82,1,PFD,0,0,0,83,True
20,Preop_CombinedLowerDLTExtremity,84,84,0,PFD,0,0,0,84,True
21,Preop_DLTLeftLowerExtremities,84,84,0,PFD,0,0,0,84,True
22,Preop_DLTRightLowerExtremities,84,84,0,PFD,0,0,0,84,True
23,Preop_DeficitToPinprickUpperLeft,84,84,0,PFD,0,0,0,84,True
24,Preop_DeficitToPinprickUpperRight,84,83,1,PFD,0,0,0,84,True
25,Preop_DeficittoPinprickLowerLeft,84,84,0,PFD,0,0,0,84,True
26,Preop_DeficittoPinprickLowerRight,84,84,0,PFD,0,0,0,84,True
27,Preop_LightTouchTorso,84,84,0,PFD,0,0,0,84,True
28,Preop_LightTouchSaddle,84,84,0,PFD,0,0,0,84,True
29,Preop_DeepTendonReflexes,83,82,1,PFD,0,0,0,83,True
30,Preop_AnkleClonus,82,81,1,PFD,0,0,0,82,True
31,Preop_GaitInstability,80,80,0,PFD,0,0,0,80,True

In [35]:
pfdd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group,Resolved,Improved,Unknown,TotalCounted,equal
0,Preop_Papilledema,77,77,0,PFDD,0,0,0,0,0
1,Preop_Nystagmus,73,73,0,PFDD,0,0,0,0,0
2,Preop_DisconjugateGaze,77,77,0,PFDD,0,0,0,0,0
3,Preop_ExtraocularPalsies,76,76,0,PFDD,0,0,0,0,0
4,Preop_FacialWeakness,78,78,0,PFDD,0,0,0,0,0
5,Preop_DisturbanceInFacialSensation,78,78,0,PFDD,0,0,0,0,0
6,Preop_HearingLoss,77,77,0,PFDD,0,0,0,0,0
7,Preop_Hoarseness_x,77,77,0,PFDD,0,0,0,0,0
8,Preop_TongueDeviation,78,78,0,PFDD,0,0,0,0,0
9,Preop_WeakShrug,78,78,0,PFDD,0,0,0,0,0
10,Preop_CombinedUpperExtremityWeak,76,76,0,PFDD,0,0,0,0,0
11,Preop_LeftUpperExtremityWeak,78,78,0,PFDD,0,0,0,0,0
12,Preop_RightUpperExtremityWeak,76,76,0,PFDD,0,0,0,0,0
13,Preop_CombinedLowerExtremityWeak,78,78,0,PFDD,0,0,0,0,0
14,Preop_LeftLowerExtremityWeak,78,78,0,PFDD,0,0,0,0,0
15,Preop_RightLowerExtremityWeak,78,78,0,PFDD,0,0,0,0,0
16,Preop_LighttouchEntireBody,78,78,0,PFDD,0,0,0,0,0
17,Preop_CombinedUpperDLTExtremity,75,75,0,PFDD,0,0,0,0,0
18,Preop_DLTLeftUpperExtremities,76,76,0,PFDD,0,0,0,0,0
19,Preop_DLTRightUpperExtremities,76,76,0,PFDD,0,0,0,0,0
20,Preop_CombinedLowerDLTExtremity,78,78,0,PFDD,0,0,0,0,0
21,Preop_DLTLeftLowerExtremities,78,78,0,PFDD,0,0,0,0,0
22,Preop_DLTRightLowerExtremities,78,78,0,PFDD,0,0,0,0,0
23,Preop_DeficitToPinprickUpperLeft,78,78,0,PFDD,0,0,0,0,0
24,Preop_DeficitToPinprickUpperRight,78,78,0,PFDD,0,0,0,0,0
25,Preop_DeficittoPinprickLowerLeft,78,78,0,PFDD,0,0,0,0,0
26,Preop_DeficittoPinprickLowerRight,78,78,0,PFDD,0,0,0,0,0
27,Preop_LightTouchTorso,78,78,0,PFDD,0,0,0,0,0
28,Preop_LightTouchSaddle,78,78,0,PFDD,0,0,0,0,0
29,Preop_DeepTendonReflexes,71,69,2,PFDD,0,0,0,0,0
30,Preop_AnkleClonus,77,77,0,PFDD,0,0,0,0,0
31,Preop_GaitInstability,69,68,1,PFDD,0,0,0,0,0

In [36]:
pfd_summary_ordered.to_csv('250930_no_preop_pfd_summary_table2_neurological_exam.csv',index=False)

In [37]:
pfdd_summary_ordered.to_csv('250930_no_preop_pfdd_summary_table2_neurological_exam.csv',index=False)

In [38]:
pfd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group,Resolved,Improved,Unknown,TotalCounted,equal
0,Preop_Papilledema,83,83,0,PFD,0,0,0,83,True
1,Preop_Nystagmus,80,80,0,PFD,0,0,0,80,True
2,Preop_DisconjugateGaze,83,82,1,PFD,0,0,0,83,True
3,Preop_ExtraocularPalsies,82,82,0,PFD,0,0,0,82,True
4,Preop_FacialWeakness,84,84,0,PFD,0,0,0,84,True
5,Preop_DisturbanceInFacialSensation,83,83,0,PFD,0,0,0,83,True
6,Preop_HearingLoss,83,83,0,PFD,0,0,0,83,True
7,Preop_Hoarseness_x,82,82,0,PFD,0,0,0,82,True
8,Preop_TongueDeviation,84,84,0,PFD,0,0,0,84,True
9,Preop_WeakShrug,84,84,0,PFD,0,0,0,84,True
10,Preop_CombinedUpperExtremityWeak,82,82,0,PFD,0,0,0,82,True
11,Preop_LeftUpperExtremityWeak,83,83,0,PFD,0,0,0,83,True
12,Preop_RightUpperExtremityWeak,83,83,0,PFD,0,0,0,83,True
13,Preop_CombinedLowerExtremityWeak,84,83,1,PFD,0,0,0,84,True
14,Preop_LeftLowerExtremityWeak,84,83,1,PFD,0,0,0,84,True
15,Preop_RightLowerExtremityWeak,84,84,0,PFD,0,0,0,84,True
16,Preop_LighttouchEntireBody,84,84,0,PFD,0,0,0,84,True
17,Preop_CombinedUpperDLTExtremity,82,81,1,PFD,0,0,0,82,True
18,Preop_DLTLeftUpperExtremities,83,83,0,PFD,0,0,0,83,True
19,Preop_DLTRightUpperExtremities,83,82,1,PFD,0,0,0,83,True
20,Preop_CombinedLowerDLTExtremity,84,84,0,PFD,0,0,0,84,True
21,Preop_DLTLeftLowerExtremities,84,84,0,PFD,0,0,0,84,True
22,Preop_DLTRightLowerExtremities,84,84,0,PFD,0,0,0,84,True
23,Preop_DeficitToPinprickUpperLeft,84,84,0,PFD,0,0,0,84,True
24,Preop_DeficitToPinprickUpperRight,84,83,1,PFD,0,0,0,84,True
25,Preop_DeficittoPinprickLowerLeft,84,84,0,PFD,0,0,0,84,True
26,Preop_DeficittoPinprickLowerRight,84,84,0,PFD,0,0,0,84,True
27,Preop_LightTouchTorso,84,84,0,PFD,0,0,0,84,True
28,Preop_LightTouchSaddle,84,84,0,PFD,0,0,0,84,True
29,Preop_DeepTendonReflexes,83,82,1,PFD,0,0,0,83,True
30,Preop_AnkleClonus,82,81,1,PFD,0,0,0,82,True
31,Preop_GaitInstability,80,80,0,PFD,0,0,0,80,True

In [39]:
pfdd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Stable,Worse,Group,Resolved,Improved,Unknown,TotalCounted,equal
0,Preop_Papilledema,77,77,0,PFDD,0,0,0,0,0
1,Preop_Nystagmus,73,73,0,PFDD,0,0,0,0,0
2,Preop_DisconjugateGaze,77,77,0,PFDD,0,0,0,0,0
3,Preop_ExtraocularPalsies,76,76,0,PFDD,0,0,0,0,0
4,Preop_FacialWeakness,78,78,0,PFDD,0,0,0,0,0
5,Preop_DisturbanceInFacialSensation,78,78,0,PFDD,0,0,0,0,0
6,Preop_HearingLoss,77,77,0,PFDD,0,0,0,0,0
7,Preop_Hoarseness_x,77,77,0,PFDD,0,0,0,0,0
8,Preop_TongueDeviation,78,78,0,PFDD,0,0,0,0,0
9,Preop_WeakShrug,78,78,0,PFDD,0,0,0,0,0
10,Preop_CombinedUpperExtremityWeak,76,76,0,PFDD,0,0,0,0,0
11,Preop_LeftUpperExtremityWeak,78,78,0,PFDD,0,0,0,0,0
12,Preop_RightUpperExtremityWeak,76,76,0,PFDD,0,0,0,0,0
13,Preop_CombinedLowerExtremityWeak,78,78,0,PFDD,0,0,0,0,0
14,Preop_LeftLowerExtremityWeak,78,78,0,PFDD,0,0,0,0,0
15,Preop_RightLowerExtremityWeak,78,78,0,PFDD,0,0,0,0,0
16,Preop_LighttouchEntireBody,78,78,0,PFDD,0,0,0,0,0
17,Preop_CombinedUpperDLTExtremity,75,75,0,PFDD,0,0,0,0,0
18,Preop_DLTLeftUpperExtremities,76,76,0,PFDD,0,0,0,0,0
19,Preop_DLTRightUpperExtremities,76,76,0,PFDD,0,0,0,0,0
20,Preop_CombinedLowerDLTExtremity,78,78,0,PFDD,0,0,0,0,0
21,Preop_DLTLeftLowerExtremities,78,78,0,PFDD,0,0,0,0,0
22,Preop_DLTRightLowerExtremities,78,78,0,PFDD,0,0,0,0,0
23,Preop_DeficitToPinprickUpperLeft,78,78,0,PFDD,0,0,0,0,0
24,Preop_DeficitToPinprickUpperRight,78,78,0,PFDD,0,0,0,0,0
25,Preop_DeficittoPinprickLowerLeft,78,78,0,PFDD,0,0,0,0,0
26,Preop_DeficittoPinprickLowerRight,78,78,0,PFDD,0,0,0,0,0
27,Preop_LightTouchTorso,78,78,0,PFDD,0,0,0,0,0
28,Preop_LightTouchSaddle,78,78,0,PFDD,0,0,0,0,0
29,Preop_DeepTendonReflexes,71,69,2,PFDD,0,0,0,0,0
30,Preop_AnkleClonus,77,77,0,PFDD,0,0,0,0,0
31,Preop_GaitInstability,69,68,1,PFDD,0,0,0,0,0