In [2]:
import pandas as pd
combined_df = pd.read_csv('combined_all_preop_index_new_refined_limonadi_251024.csv')

In [3]:
list(combined_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_CombinedUpperExtremityWeak',
 'Index_CombinedUpperExtremityStrength',
 'Limonadi_Index_CombinedUpperExtremityStrength',
 'New_CombinedUpperExtremityStrength',
 'Refined_CombinedUpperExtremityStrength',
 'Limonadi_CombinedUpperExtremityStrength',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_CombinedLowerExtremityWeak',
 'Index_CombinedLowerExtremityStrength',
 'Limonadi_Index_CombinedLowerExtremityStrength',
 'New_CombinedLowerExtremityStrength',
 'Refined_CombinedLowerExtremityStrength',
 'Limonadi_CombinedLowerExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_CombinedUpperDLTExtremities',
 'Index_CombinedUpperDLTExtremities',
 'Limonadi_Index_CombinedUpperDLTExtremities',
 'New_CombinedUpperDLTExtremities',
 'Refined_CombinedUpperDLTExtremities',
 'Limonadi_CombinedUpperDLTExtremities',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_CombinedLowerDLTExtremities',
 'Index_CombinedLowerDLTExtremities',
 'Limonadi_Index_CombinedLowerDLTExtremities',
 'New_CombinedLowerDLTExtremities',
 'Refined_CombinedLowerDLTExtremities',
 'Limonadi_CombinedLowerDLTExtremities',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [4]:
preop_to_refined_symptom_map = {
    "Preop_Headache": "Refined_PreviouslyReportedHeadaches",
    "Preop_DoubleVision": "Refined_DoubleVisionSymptoms",
    "Preop_SensorySymptoms": "Refined_SensoryDeficitSymptoms",
    "Preop_WeaknessSymptoms": "Refined_WeaknessSymptoms",
    "Preop_Dysphagia": "Refined_DysphagiaSymptoms",
    "Preop_Hoarseness_y": "Refined_HoarsenessSymptoms",
    "Preop_Choking": "Refined_ChokingSymptoms",
    "Preop_SleepApnea": "Refined_SleepApneaSymptoms",
    "Preop_ShortnessOfBreath": "Refined_SOBSymptoms",
    "Preop_NeckPain": "Refined_NeckPainSymptoms",
    "Preop_BackPain": "Refined_BackPainSymptoms",
    "Preop_TrunkPain": "Refined_TrunkPainSymptoms",
    "Preop_UpperExtremityPain": "Refined_UpperExtremPainSymptoms",
    "Preop_LowerExtremityPain": "Refined_LowerExtremPainSymptoms",
    "Preop_Tremors": "Refined_TremorsSymptoms",
    "Preop_BalanceOrGaitAtaxia": "Refined_GaitAtaxiaSymptoms",
    "Preop_Incontinence": "Refined_IncontinenceSymptoms",
    "Preop_SexualDysfunction": "Refined_SexualDysfunctionSymptoms",
}

In [5]:
list(combined_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_CombinedUpperExtremityWeak',
 'Index_CombinedUpperExtremityStrength',
 'Limonadi_Index_CombinedUpperExtremityStrength',
 'New_CombinedUpperExtremityStrength',
 'Refined_CombinedUpperExtremityStrength',
 'Limonadi_CombinedUpperExtremityStrength',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_CombinedLowerExtremityWeak',
 'Index_CombinedLowerExtremityStrength',
 'Limonadi_Index_CombinedLowerExtremityStrength',
 'New_CombinedLowerExtremityStrength',
 'Refined_CombinedLowerExtremityStrength',
 'Limonadi_CombinedLowerExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_CombinedUpperDLTExtremities',
 'Index_CombinedUpperDLTExtremities',
 'Limonadi_Index_CombinedUpperDLTExtremities',
 'New_CombinedUpperDLTExtremities',
 'Refined_CombinedUpperDLTExtremities',
 'Limonadi_CombinedUpperDLTExtremities',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_CombinedLowerDLTExtremities',
 'Index_CombinedLowerDLTExtremities',
 'Limonadi_Index_CombinedLowerDLTExtremities',
 'New_CombinedLowerDLTExtremities',
 'Refined_CombinedLowerDLTExtremities',
 'Limonadi_CombinedLowerDLTExtremities',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [6]:

pfd_df = combined_df[combined_df['Allocation'] == 'PFD'].copy()
pfdd_df = combined_df[combined_df['Allocation'] == 'PFDD'].copy()


pfd_df = pfd_df.dropna(subset=['SubjectId'])
pfdd_df = pfdd_df.dropna(subset=['SubjectId'])


print("PFD group:", pfd_df.shape)
print("PFDD group:", pfdd_df.shape)

PFD group: (84, 314)
PFDD group: (78, 314)

In [7]:
list(pfd_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_CombinedUpperExtremityWeak',
 'Index_CombinedUpperExtremityStrength',
 'Limonadi_Index_CombinedUpperExtremityStrength',
 'New_CombinedUpperExtremityStrength',
 'Refined_CombinedUpperExtremityStrength',
 'Limonadi_CombinedUpperExtremityStrength',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_CombinedLowerExtremityWeak',
 'Index_CombinedLowerExtremityStrength',
 'Limonadi_Index_CombinedLowerExtremityStrength',
 'New_CombinedLowerExtremityStrength',
 'Refined_CombinedLowerExtremityStrength',
 'Limonadi_CombinedLowerExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_CombinedUpperDLTExtremities',
 'Index_CombinedUpperDLTExtremities',
 'Limonadi_Index_CombinedUpperDLTExtremities',
 'New_CombinedUpperDLTExtremities',
 'Refined_CombinedUpperDLTExtremities',
 'Limonadi_CombinedUpperDLTExtremities',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_CombinedLowerDLTExtremities',
 'Index_CombinedLowerDLTExtremities',
 'Limonadi_Index_CombinedLowerDLTExtremities',
 'New_CombinedLowerDLTExtremities',
 'Refined_CombinedLowerDLTExtremities',
 'Limonadi_CombinedLowerDLTExtremities',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [8]:
# Function to generate summary table for a given group
def summarize_symptoms(df, label='Group'):
    all_summaries = []

    for pre_symptom, post_symptom in preop_to_refined_symptom_map.items():
        # filter with preoperatove data
        subset = df[df[pre_symptom] == False]
        baseline_count = subset['SubjectId'].nunique()

        temp = subset[['SubjectId', post_symptom]].fillna(5)
        temp = temp.rename(columns={post_symptom: 'Outcome'})
        temp['Outcome'] = temp['Outcome']
        temp['Symptom'] = pre_symptom

        count_df = temp.groupby('Outcome')['SubjectId'].nunique().reset_index()
        count_df['Symptom'] = pre_symptom
        count_df = count_df.rename(columns={'SubjectId': 'N_Patients'})
        count_pivot = count_df.pivot(index='Symptom', columns='Outcome', values='N_Patients')
        count_pivot['NotPresentBaseline'] = baseline_count
        all_summaries.append(count_pivot)
    # 4. Rename outcome columns
    outcome_labels = {
        1: 'Resolved',
        2: 'Improved',
        3: 'Stable',
        4: 'Worse',
        5: 'Unknown',
        0: 'Not Applicable',
        'Nan in the datasheets':'Nan in the datasheets',
        '1': 'Resolved',
        '2': 'Improved',
        '3': 'Stable',
        '4': 'Worse',
        '5': 'Unknown',
        '0': 'Not Applicable',
    }

    # 5. Reorder columns (only include if present)
    desired_order = [
        'NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse',
        'Unknown','Not Applicable'
    ]

    # Combine and rename
    summary_df = pd.concat(all_summaries).fillna(0).astype(int)
    print(list(summary_df.columns))



    summary_df = summary_df.rename(columns=outcome_labels)
    for col in desired_order:
        if col not in summary_df.columns:
            summary_df[col] = 0

    # Reorder
    summary_df = summary_df[[col for col in desired_order if col in summary_df.columns]]
    summary_df = summary_df.reset_index()
    summary_df['Group'] = label

    return summary_df


# Apply separately to each group
pfd_summary = summarize_symptoms(pfd_df, label='PFD')
pfdd_summary = summarize_symptoms(pfdd_df, label='PFDD')


combined_summary = pd.concat([pfd_summary, pfdd_summary], ignore_index=True)

pfd_summary

[3.0, 4.0, 'NotPresentBaseline']
[3.0, 4.0, 'NotPresentBaseline']

Outcome,Symptom,NotPresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Not Applicable,Group
0,Preop_Headache,32,0,0,28,4,0,0,PFD
1,Preop_DoubleVision,83,0,0,83,0,0,0,PFD
2,Preop_SensorySymptoms,65,0,0,63,2,0,0,PFD
3,Preop_WeaknessSymptoms,77,0,0,77,0,0,0,PFD
4,Preop_Dysphagia,75,0,0,75,0,0,0,PFD
5,Preop_Hoarseness_y,84,0,0,84,0,0,0,PFD
6,Preop_Choking,81,0,0,81,0,0,0,PFD
7,Preop_SleepApnea,78,0,0,77,1,0,0,PFD
8,Preop_ShortnessOfBreath,82,0,0,82,0,0,0,PFD
9,Preop_NeckPain,63,0,0,62,1,0,0,PFD
10,Preop_BackPain,71,0,0,69,2,0,0,PFD
11,Preop_TrunkPain,84,0,0,84,0,0,0,PFD
12,Preop_UpperExtremityPain,79,0,0,77,2,0,0,PFD
13,Preop_LowerExtremityPain,74,0,0,73,1,0,0,PFD
14,Preop_Tremors,83,0,0,81,2,0,0,PFD
15,Preop_BalanceOrGaitAtaxia,75,0,0,74,1,0,0,PFD
16,Preop_Incontinence,81,0,0,81,0,0,0,PFD
17,Preop_SexualDysfunction,84,0,0,84,0,0,0,PFD

In [9]:
pfd_df

,SubjectId,Preop_Papilledema,Index_Papilledema,Limonadi_Index_Papilledema,Refined_Papilledema,Limonadi_Papilledema,Preop_Nystagmus,Index_Nystagmus,Limonadi_Index_Nystagmus,Refined_Nystagmus,...,Refined_IncontinenceSymptoms,Limonadi_IncontinenceSymptoms,Preop_SexualDysfunction,IndexSexualDysfunctionSymptoms,Limonadi_Index_SexualDysfunctionSymptoms,Overall_SexualDysfunctionSymp,Limonadi_Overall_SexualDysfunctionSymp,Refined_SexualDysfunctionSymptoms,Limonadi_SexualDysfunctionSymptoms,none_preop
0,1,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
1,2,0,3.0,0.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
4,5,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,1
5,6,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
6,7,0,3.0,0.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,159,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
155,162,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
157,164,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
159,166,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
160,167,0,5.0,5.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0

In [10]:
pfdd_summary

Outcome,Symptom,NotPresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Not Applicable,Group
0,Preop_Headache,26,0,0,23,3,0,0,PFDD
1,Preop_DoubleVision,74,0,0,74,0,0,0,PFDD
2,Preop_SensorySymptoms,51,0,0,50,1,0,0,PFDD
3,Preop_WeaknessSymptoms,68,0,0,68,0,0,0,PFDD
4,Preop_Dysphagia,69,0,0,69,0,0,0,PFDD
5,Preop_Hoarseness_y,76,0,0,76,0,0,0,PFDD
6,Preop_Choking,76,0,0,76,0,0,0,PFDD
7,Preop_SleepApnea,74,0,0,74,0,0,0,PFDD
8,Preop_ShortnessOfBreath,75,0,0,75,0,0,0,PFDD
9,Preop_NeckPain,52,0,0,48,4,0,0,PFDD
10,Preop_BackPain,58,0,0,54,4,0,0,PFDD
11,Preop_TrunkPain,73,0,0,73,0,0,0,PFDD
12,Preop_UpperExtremityPain,73,0,0,71,2,0,0,PFDD
13,Preop_LowerExtremityPain,74,0,0,72,2,0,0,PFDD
14,Preop_Tremors,75,0,0,75,0,0,0,PFDD
15,Preop_BalanceOrGaitAtaxia,61,0,0,59,2,0,0,PFDD
16,Preop_Incontinence,69,0,0,68,1,0,0,PFDD
17,Preop_SexualDysfunction,78,0,0,78,0,0,0,PFDD

In [11]:
# Define all outcome-related columns to sum
outcome_cols = [
    'Resolved',
    'Improved',
    'Stable',
    'Worse',
    'Unknown',
]

# Check for mismatches in PFD
pfd_summary['TotalCounted'] = pfd_summary[outcome_cols].sum(axis=1)
pfd_summary['equal'] = pfd_summary['TotalCounted'] == pfd_summary['NotPresentBaseline'] 


# Check for mismatches in PFDD
pfdd_summary['TotalCounted'] = pfdd_summary[outcome_cols].sum(axis=1)
pfdd_summary['equal'] = pfdd_summary['TotalCounted'] == pfdd_summary['NotPresentBaseline']

In [12]:
desired_order = list(preop_to_refined_symptom_map.keys())

# Ensure all needed columns exist
required_columns = ['Symptom', 'NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'Group', 'TotalCounted', 'equal']
for col in required_columns:
    if col not in pfd_summary.columns:
        pfd_summary[col] = 0

# Set index to 'Symptom' for easy reindexing
pfd_summary.set_index('Symptom', inplace=True)

# Reindex with desired order and fill all missing values with NaN (temporarily)
pfd_summary_ordered = pfd_summary.reindex(desired_order).reset_index()

# Fill missing values in specific columns first
pfd_summary_ordered['Group'] = pfd_summary_ordered['Group'].fillna('PFD')
pfd_summary_ordered['equal'] = pfd_summary_ordered['equal'].fillna(True)

# Fill remaining numeric columns with 0
pfd_summary_ordered.fillna(0, inplace=True)

# Convert appropriate columns to integers (if needed)
int_cols = ['NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'TotalCounted']
pfd_summary_ordered[int_cols] = pfd_summary_ordered[int_cols].astype(int)

In [13]:
pfd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Not Applicable,Group,TotalCounted,equal
0,Preop_Headache,32,0,0,28,4,0,0,PFD,32,True
1,Preop_DoubleVision,83,0,0,83,0,0,0,PFD,83,True
2,Preop_SensorySymptoms,65,0,0,63,2,0,0,PFD,65,True
3,Preop_WeaknessSymptoms,77,0,0,77,0,0,0,PFD,77,True
4,Preop_Dysphagia,75,0,0,75,0,0,0,PFD,75,True
5,Preop_Hoarseness_y,84,0,0,84,0,0,0,PFD,84,True
6,Preop_Choking,81,0,0,81,0,0,0,PFD,81,True
7,Preop_SleepApnea,78,0,0,77,1,0,0,PFD,78,True
8,Preop_ShortnessOfBreath,82,0,0,82,0,0,0,PFD,82,True
9,Preop_NeckPain,63,0,0,62,1,0,0,PFD,63,True
10,Preop_BackPain,71,0,0,69,2,0,0,PFD,71,True
11,Preop_TrunkPain,84,0,0,84,0,0,0,PFD,84,True
12,Preop_UpperExtremityPain,79,0,0,77,2,0,0,PFD,79,True
13,Preop_LowerExtremityPain,74,0,0,73,1,0,0,PFD,74,True
14,Preop_Tremors,83,0,0,81,2,0,0,PFD,83,True
15,Preop_BalanceOrGaitAtaxia,75,0,0,74,1,0,0,PFD,75,True
16,Preop_Incontinence,81,0,0,81,0,0,0,PFD,81,True
17,Preop_SexualDysfunction,84,0,0,84,0,0,0,PFD,84,True

In [14]:
pfd_summary_ordered.to_csv('250930_no_preop_pfd_summary_table2_symptoms.csv',index=False)

In [15]:
pfd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Not Applicable,Group,TotalCounted,equal
0,Preop_Headache,32,0,0,28,4,0,0,PFD,32,True
1,Preop_DoubleVision,83,0,0,83,0,0,0,PFD,83,True
2,Preop_SensorySymptoms,65,0,0,63,2,0,0,PFD,65,True
3,Preop_WeaknessSymptoms,77,0,0,77,0,0,0,PFD,77,True
4,Preop_Dysphagia,75,0,0,75,0,0,0,PFD,75,True
5,Preop_Hoarseness_y,84,0,0,84,0,0,0,PFD,84,True
6,Preop_Choking,81,0,0,81,0,0,0,PFD,81,True
7,Preop_SleepApnea,78,0,0,77,1,0,0,PFD,78,True
8,Preop_ShortnessOfBreath,82,0,0,82,0,0,0,PFD,82,True
9,Preop_NeckPain,63,0,0,62,1,0,0,PFD,63,True
10,Preop_BackPain,71,0,0,69,2,0,0,PFD,71,True
11,Preop_TrunkPain,84,0,0,84,0,0,0,PFD,84,True
12,Preop_UpperExtremityPain,79,0,0,77,2,0,0,PFD,79,True
13,Preop_LowerExtremityPain,74,0,0,73,1,0,0,PFD,74,True
14,Preop_Tremors,83,0,0,81,2,0,0,PFD,83,True
15,Preop_BalanceOrGaitAtaxia,75,0,0,74,1,0,0,PFD,75,True
16,Preop_Incontinence,81,0,0,81,0,0,0,PFD,81,True
17,Preop_SexualDysfunction,84,0,0,84,0,0,0,PFD,84,True

In [16]:
pfdd_summary

Outcome,Symptom,NotPresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Not Applicable,Group,TotalCounted,equal
0,Preop_Headache,26,0,0,23,3,0,0,PFDD,26,True
1,Preop_DoubleVision,74,0,0,74,0,0,0,PFDD,74,True
2,Preop_SensorySymptoms,51,0,0,50,1,0,0,PFDD,51,True
3,Preop_WeaknessSymptoms,68,0,0,68,0,0,0,PFDD,68,True
4,Preop_Dysphagia,69,0,0,69,0,0,0,PFDD,69,True
5,Preop_Hoarseness_y,76,0,0,76,0,0,0,PFDD,76,True
6,Preop_Choking,76,0,0,76,0,0,0,PFDD,76,True
7,Preop_SleepApnea,74,0,0,74,0,0,0,PFDD,74,True
8,Preop_ShortnessOfBreath,75,0,0,75,0,0,0,PFDD,75,True
9,Preop_NeckPain,52,0,0,48,4,0,0,PFDD,52,True
10,Preop_BackPain,58,0,0,54,4,0,0,PFDD,58,True
11,Preop_TrunkPain,73,0,0,73,0,0,0,PFDD,73,True
12,Preop_UpperExtremityPain,73,0,0,71,2,0,0,PFDD,73,True
13,Preop_LowerExtremityPain,74,0,0,72,2,0,0,PFDD,74,True
14,Preop_Tremors,75,0,0,75,0,0,0,PFDD,75,True
15,Preop_BalanceOrGaitAtaxia,61,0,0,59,2,0,0,PFDD,61,True
16,Preop_Incontinence,69,0,0,68,1,0,0,PFDD,69,True
17,Preop_SexualDysfunction,78,0,0,78,0,0,0,PFDD,78,True

In [17]:
desired_order = list(preop_to_refined_symptom_map.keys())

# Ensure all needed columns exist
required_columns = ['Symptom', 'NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'Group', 'TotalCounted', 'equal']
for col in required_columns:
    if col not in pfdd_summary.columns:
        pfdd_summary[col] = 0

# Set index to 'Symptom' for easy reindexing
pfdd_summary.set_index('Symptom', inplace=True)

# Reindex with desired order and fill all missing values with NaN (temporarily)
pfdd_summary_ordered = pfdd_summary.reindex(desired_order).reset_index()

# Fill missing values in specific columns first
pfdd_summary_ordered['Group'] = pfdd_summary_ordered['Group'].fillna('PFDD')
pfdd_summary_ordered['equal'] = pfdd_summary_ordered['equal'].fillna(True)

# Fill remaining numeric columns with 0
pfdd_summary_ordered.fillna(0, inplace=True)

# Convert appropriate columns to integers (if needed)
int_cols = ['NotPresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'TotalCounted']
pfdd_summary_ordered[int_cols] = pfdd_summary_ordered[int_cols].astype(int)

In [18]:
pfdd_summary_ordered

Outcome,Symptom,NotPresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Not Applicable,Group,TotalCounted,equal
0,Preop_Headache,26,0,0,23,3,0,0,PFDD,26,True
1,Preop_DoubleVision,74,0,0,74,0,0,0,PFDD,74,True
2,Preop_SensorySymptoms,51,0,0,50,1,0,0,PFDD,51,True
3,Preop_WeaknessSymptoms,68,0,0,68,0,0,0,PFDD,68,True
4,Preop_Dysphagia,69,0,0,69,0,0,0,PFDD,69,True
5,Preop_Hoarseness_y,76,0,0,76,0,0,0,PFDD,76,True
6,Preop_Choking,76,0,0,76,0,0,0,PFDD,76,True
7,Preop_SleepApnea,74,0,0,74,0,0,0,PFDD,74,True
8,Preop_ShortnessOfBreath,75,0,0,75,0,0,0,PFDD,75,True
9,Preop_NeckPain,52,0,0,48,4,0,0,PFDD,52,True
10,Preop_BackPain,58,0,0,54,4,0,0,PFDD,58,True
11,Preop_TrunkPain,73,0,0,73,0,0,0,PFDD,73,True
12,Preop_UpperExtremityPain,73,0,0,71,2,0,0,PFDD,73,True
13,Preop_LowerExtremityPain,74,0,0,72,2,0,0,PFDD,74,True
14,Preop_Tremors,75,0,0,75,0,0,0,PFDD,75,True
15,Preop_BalanceOrGaitAtaxia,61,0,0,59,2,0,0,PFDD,61,True
16,Preop_Incontinence,69,0,0,68,1,0,0,PFDD,69,True
17,Preop_SexualDysfunction,78,0,0,78,0,0,0,PFDD,78,True

In [19]:
pfdd_summary_ordered.to_csv('250930_no_preop_pfdd_summary_table2_symptoms.csv',index=False)

In [20]:
for pre_symptom, post_symptom in preop_to_refined_symptom_map.items():
    subset = pfd_df[pfd_df[pre_symptom] == False]
    baseline_count = subset['SubjectId'].nunique()

    temp = subset[['SubjectId', post_symptom]].copy()
    temp[post_symptom] = temp[post_symptom].fillna('Nan in the datasheets').astype(str)
    
    # Desired order as strings
    order = ['0.0','1.0', '2.0', '3.0', '4.0', '5.0', 'Nan in the datasheets']
    
    # Compute and reindex
    counts = temp[post_symptom].value_counts().reindex(order, fill_value=0)
    print(counts)

Refined_PreviouslyReportedHeadaches
0.0                       0
1.0                       0
2.0                       0
3.0                      28
4.0                       4
5.0                       0
Nan in the datasheets     0
Name: count, dtype: int64
Refined_DoubleVisionSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_SensoryDeficitSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_WeaknessSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_DysphagiaSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_HoarsenessSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_ChokingSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_SleepApneaSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_SOBSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_NeckPainSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_BackPainSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_TrunkPainSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_UpperExtremPainSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_LowerExtremPainSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_TremorsSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_GaitAtaxiaSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_IncontinenceSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64
Refined_SexualDysfunctionSymptoms
0.0                      0
1.0                      0
2.0                      0
3.0                      0
4.0                      0
5.0                      0
Nan in the datasheets    0
Name: count, dtype: int64