# Load data

In [3]:
import pandas as pd
combined_df = pd.read_csv('combined_all_preop_index_new_refined_limonadi_251024.csv')
# combined_df = combined_df.drop(columns=['CombinedUpperExtremityWeak_preop','CombinedLowerExtremityWeak_preop','CombinedUpperDLTExtremities_preop','CombinedLowerDLTExtremities_preop',
#                                          'CombinedUpperExtremityStrength',
#  'CombinedLowerExtremityStrength',
#  'CombinedUpperDLTExtremity',
#  'CombinedLowerDLTExtremity'])
combined_df = combined_df.drop(columns=[col for col in combined_df.columns if 'Combined' in col])

In [4]:
combined_df

,SubjectId,Preop_Papilledema,Index_Papilledema,Limonadi_Index_Papilledema,Refined_Papilledema,Limonadi_Papilledema,Preop_Nystagmus,Index_Nystagmus,Limonadi_Index_Nystagmus,Refined_Nystagmus,...,Refined_IncontinenceSymptoms,Limonadi_IncontinenceSymptoms,Preop_SexualDysfunction,IndexSexualDysfunctionSymptoms,Limonadi_Index_SexualDysfunctionSymptoms,Overall_SexualDysfunctionSymp,Limonadi_Overall_SexualDysfunctionSymp,Refined_SexualDysfunctionSymptoms,Limonadi_SexualDysfunctionSymptoms,none_preop
0,1,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
1,2,0,3.0,0.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
2,3,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
3,4,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,1
4,5,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,164,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
158,165,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
159,166,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
160,167,0,5.0,5.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
161,168,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0

In [5]:
list(combined_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [6]:
combined_df.Allocation.value_counts()

Allocation
PFD     84
PFDD    78
Name: count, dtype: int64

In [7]:
preop_to_refined_neuro_map = {
    "Preop_Papilledema": "Refined_Papilledema",
    "Preop_Nystagmus": "Refined_Nystagmus",
    "Preop_DisconjugateGaze": "Refined_DisconjugateGaze",
    "Preop_ExtraocularPalsies": "Refined_DocExtraOcPalsies",
    "Preop_FacialWeakness": "Refined_FacialWeakness",
    "Preop_DisturbanceInFacialSensation": "Refined_DisturbanceFacSen",
    "Preop_HearingLoss": "Refined_HearingLoss",
    "Preop_Hoarseness_x": "Refined_Hoarseness",
    "Preop_TongueDeviation": "Refined_TongueDeviation",
    "Preop_WeakShrug": "Refined_WeakShrug",

    "Preop_LeftUpperExtremityWeak": "Refined_LeftUpperExtremityStrength",
    "Preop_RightUpperExtremityWeak": "Refined_RightUpperExtremityStrength",
    "Preop_LeftLowerExtremityWeak": "Refined_LeftLowerExtremityStrength",
    "Preop_RightLowerExtremityWeak": "Refined_RightLowerExtremityStrength",

    "Preop_LighttouchEntireBody": "Refined_DeficitToLightTouchEntireBody",
    "Preop_DLTLeftUpperExtremities": "Refined_LightTouchSensoryDeficitLUE",
    "Preop_DLTRightUpperExtremities": "Refined_LightTouchSensoryDeficitRUE",
    "Preop_DLTLeftLowerExtremities": "Refined_LightTouchSensoryDeficitLLE",
    "Preop_DLTRightLowerExtremities": "Refined_LightTouchSensoryDeficitRLE",

    "Preop_DeficitToPinprickUpperLeft": "Refined_LUEDeficitPinprick",
    "Preop_DeficitToPinprickUpperRight": "Refined_RUEDeficitPinprick",
    "Preop_DeficittoPinprickLowerLeft": "Refined_LLEDeficitPinprick",
    "Preop_DeficittoPinprickLowerRight": "Refined_RLEDeficitPinprick",

    "Preop_LightTouchTorso": "Refined_DeficitLightTouchTorso",
    "Preop_LightTouchSaddle": "Refined_DeficitLightTouchTorso",

    "Preop_DeepTendonReflexes": "Refined_DeepTendonReflexes",
    "Preop_AnkleClonus": "Refined_FUAnkleClonus",
    "Preop_GaitInstability": "Refined_GaitStatus",
}

In [8]:

pfd_df = combined_df[combined_df['Allocation'] == 'PFD'].copy()
pfdd_df = combined_df[combined_df['Allocation'] == 'PFDD'].copy()


pfd_df = pfd_df.dropna(subset=['SubjectId'])
pfdd_df = pfdd_df.dropna(subset=['SubjectId'])


print("PFD group:", pfd_df.shape)
print("PFDD group:", pfdd_df.shape)

PFD group: (84, 290)
PFDD group: (78, 290)

In [9]:
pfd_df

,SubjectId,Preop_Papilledema,Index_Papilledema,Limonadi_Index_Papilledema,Refined_Papilledema,Limonadi_Papilledema,Preop_Nystagmus,Index_Nystagmus,Limonadi_Index_Nystagmus,Refined_Nystagmus,...,Refined_IncontinenceSymptoms,Limonadi_IncontinenceSymptoms,Preop_SexualDysfunction,IndexSexualDysfunctionSymptoms,Limonadi_Index_SexualDysfunctionSymptoms,Overall_SexualDysfunctionSymp,Limonadi_Overall_SexualDysfunctionSymp,Refined_SexualDysfunctionSymptoms,Limonadi_SexualDysfunctionSymptoms,none_preop
0,1,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
1,2,0,3.0,0.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
4,5,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,1
5,6,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
6,7,0,3.0,0.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,159,0,5.0,5.0,3,0,0,3.0,0.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0
155,162,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
157,164,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
159,166,0,3.0,0.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,5.0,5.0,3,0.0,0
160,167,0,5.0,5.0,3,0,0,5.0,5.0,3.0,...,3,0.0,0.0,0.0,0.0,3.0,0.0,3,0.0,0

In [10]:
list(pfd_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [11]:
list(pfd_df)

['SubjectId',
 'Preop_Papilledema',
 'Index_Papilledema',
 'Limonadi_Index_Papilledema',
 'Refined_Papilledema',
 'Limonadi_Papilledema',
 'Preop_Nystagmus',
 'Index_Nystagmus',
 'Limonadi_Index_Nystagmus',
 'Refined_Nystagmus',
 'Limonadi_Nystagmus',
 'Preop_DisconjugateGaze',
 'Index_DisconjugateGaze',
 'Limonadi_Index_DisconjugateGaze',
 'Refined_DisconjugateGaze',
 'Limonadi_DisconjugateGaze',
 'Preop_ExtraocularPalsies',
 'Index_DocExtraOcPalsies',
 'Limonadi_Index_DocExtraOcPalsies',
 'Refined_DocExtraOcPalsies',
 'Limonadi_DocExtraOcPalsies',
 'Preop_FacialWeakness',
 'Index_FacialWeakness',
 'Limonadi_Index_FacialWeakness',
 'New_FacialWeakness',
 'Refined_FacialWeakness',
 'Limonadi_FacialWeakness',
 'Preop_DisturbanceInFacialSensation',
 'New_DisturbanceInFacialSensation',
 'Index_DisturbanceFacSen',
 'Limonadi_Index_DisturbanceFacSen',
 'Refined_DisturbanceFacSen',
 'Limonadi_DisturbanceFacSen',
 'Preop_HearingLoss',
 'Index_HearingLoss',
 'Limonadi_Index_HearingLoss',
 'New_HearingLoss',
 'Refined_HearingLoss',
 'Limonadi_HearingLoss',
 'Preop_Hoarseness_x',
 'Index_Hoarseness',
 'Limonadi_Index_Hoarseness',
 'New_Hoarseness',
 'Refined_Hoarseness',
 'Limonadi_Hoarseness',
 'Preop_TongueDeviation',
 'Index_TongueDeviation',
 'Limonadi_Index_TongueDeviation',
 'New_TongueDeviation',
 'Refined_TongueDeviation',
 'Limonadi_TongueDeviation',
 'Preop_WeakShrug',
 'Index_WeakShrug',
 'Limonadi_Index_WeakShrug',
 'New_WeakShrug',
 'Refined_WeakShrug',
 'Limonadi_WeakShrug',
 'Preop_LeftUpperExtremityWeak',
 'Index_LeftUpperExtremityStrength',
 'Limonadi_Index_LeftUpperExtremityStrength',
 'New_LeftUpperExtremityStrength',
 'Refined_LeftUpperExtremityStrength',
 'Limonadi_LeftUpperExtremityStrength',
 'Preop_RightUpperExtremityWeak',
 'Index_RightUpperExtremityStrength',
 'Limonadi_Index_RightUpperExtremityStrength',
 'New_RightUpperExtremityStrength',
 'Refined_RightUpperExtremityStrength',
 'Limonadi_RightUpperExtremityStrength',
 'Preop_LeftLowerExtremityWeak',
 'Index_LeftLowerExtremityStrength',
 'Limonadi_Index_LeftLowerExtremityStrength',
 'New_LeftLowerExtremityStrength',
 'Refined_LeftLowerExtremityStrength',
 'Limonadi_LeftLowerExtremityStrength',
 'Preop_RightLowerExtremityWeak',
 'Index_RightLowerExtremityStrength',
 'Limonadi_Index_RightLowerExtremityStrength',
 'New_RightLowerExtremityStrength',
 'Refined_RightLowerExtremityStrength',
 'Limonadi_RightLowerExtremityStrength',
 'Preop_LighttouchEntireBody',
 'Index_DeficitToLightTouchEntireBody',
 'Limonadi_Index_DeficitToLightTouchEntireBody',
 'New_LighttouchEntireBody',
 'Refined_DeficitToLightTouchEntireBody',
 'Limonadi_DeficitToLightTouchEntireBody',
 'Preop_DLTLeftUpperExtremities',
 'Index_LightTouchSensoryDeficitLUE',
 'Limonadi_Index_LightTouchSensoryDeficitLUE',
 'New_DLTLeftUpperExtremities',
 'Refined_LightTouchSensoryDeficitLUE',
 'Limonadi_LightTouchSensoryDeficitLUE',
 'Preop_DLTRightUpperExtremities',
 'Index_LightTouchSensoryDeficitRUE',
 'Limonadi_Index_LightTouchSensoryDeficitRUE',
 'New_DLTRightUpperExtremities',
 'Refined_LightTouchSensoryDeficitRUE',
 'Limonadi_LightTouchSensoryDeficitRUE',
 'Preop_DLTLeftLowerExtremities',
 'Index_LightTouchSensoryDeficitLLE',
 'Limonadi_Index_LightTouchSensoryDeficitLLE',
 'New_DLTLeftLowerExtremities',
 'Refined_LightTouchSensoryDeficitLLE',
 'Limonadi_LightTouchSensoryDeficitLLE',
 'Preop_DLTRightLowerExtremities',
 'Index_LightTouchSensoryDeficitRLE',
 'Limonadi_Index_LightTouchSensoryDeficitRLE',
 'New_DLTRightLowerExtremities',
 'Refined_LightTouchSensoryDeficitRLE',
 'Limonadi_LightTouchSensoryDeficitRLE',
 'Preop_DeficitToPinprickUpperLeft',
 'Index_LUEDeficitPinprick',
 'Limonadi_Index_LUEDeficitPinprick',
 'New_DeficitToPinprickUpperLeft',
 'Refined_LUEDeficitPinprick',
 'Limonadi_LUEDeficitPinprick',
 'Preop_DeficitToPinprickUpperRight',
 'Index_RUEDeficitPinprick',
 'Limonadi_Index_RUEDeficitPinprick',
 'New_DeficitToPinprickUpperRight',
 'Refined_RUEDeficitPinprick',
 'Limonadi_RUEDeficitPinprick',
 'Preop_DeficittoPinprickLowerLeft',
 'Index_LLEDeficitPinprick',
 'Limonadi_Index_LLEDeficitPinprick',
 'New_DeficittoPinprickLowerLeft',
 'Refined_LLEDeficitPinprick',
 'Limonadi_LLEDeficitPinprick',
 'Preop_DeficittoPinprickLowerRight',
 'Index_RLEDeficitPinprick',
 'Limonadi_Index_RLEDeficitPinprick',
 'New_DeficittoPinprickLowerRight',
 'Refined_RLEDeficitPinprick',
 'Limonadi_RLEDeficitPinprick',
 'Preop_LightTouchTorso',
 'Index_DeficitLightTouchTorso',
 'Limonadi_Index_DeficitLightTouchTorso',
 'New_LightTouchTorso',
 'Refined_DeficitLightTouchTorso',
 'Limonadi_DeficitLightTouchTorso',
 'Preop_LightTouchSaddle',
 'Index_DeficitLIghtTouchSaddle',
 'Limonadi_Index_DeficitLIghtTouchSaddle',
 'New_LightTouchSaddle',
 'Refined_DeficitLIghtTouchSaddle',
 'Limonadi_DeficitLIghtTouchSaddle',
 'Preop_DeepTendonReflexes',
 'Index_DeepTendonReflexes',
 'Limonadi_Index_DeepTendonReflexes',
 'New_DeepTendonReflexes',
 'Refined_DeepTendonReflexes',
 'Limonadi_DeepTendonReflexes',
 'Preop_AnkleClonus',
 'Index_FUAnkleClonus',
 'Limonadi_Index_FUAnkleClonus',
 'Refined_FUAnkleClonus',
 'Limonadi_FUAnkleClonus',
 'Preop_GaitInstability',
 'Index_GaitStatus',
 'Limonadi_Index_GaitStatus',
 'Refined_GaitStatus',
 'Limonadi_GaitStatus',
 'Site',
 'Allocation',
 'Preop_Headache',
 'PreviouslyReportedHeadaches',
 'NewHeadache',
 'Refined_PreviouslyReportedHeadaches',
 'Limonadi_PreviouslyReportedHeadaches',
 'Preop_DoubleVision',
 'IndexDoubleVisionSymptoms',
 'Limonadi_Index_DoubleVisionSymptoms',
 'Overall_DoubleVision',
 'Limonadi_Overall_DoubleVision',
 'Refined_DoubleVisionSymptoms',
 'Limonadi_DoubleVisionSymptoms',
 'Preop_SensorySymptoms',
 'IndexSensoryDeficitSymptoms',
 'Limonadi_Index_SensoryDeficitSymptoms',
 'Overall_SensorySymptoms',
 'Limonadi_Overall_SensorySymptoms',
 'Refined_SensoryDeficitSymptoms',
 'Limonadi_SensoryDeficitSymptoms',
 'Preop_WeaknessSymptoms',
 'IndexWeaknessSymptoms',
 'Limonadi_Index_WeaknessSymptoms',
 'Overall_WeaknessSymptoms',
 'Limonadi_Overall_WeaknessSymptoms',
 'Refined_WeaknessSymptoms',
 'Limonadi_WeaknessSymptoms',
 'Preop_Dysphagia',
 'IndexDysphagiaSymptoms',
 'Limonadi_Index_DysphagiaSymptoms',
 'Overall_Dysphagia',
 'Limonadi_Overall_Dysphagia',
 'Refined_DysphagiaSymptoms',
 'Limonadi_DysphagiaSymptoms',
 'Preop_Hoarseness_y',
 'IndexHoarsenessSymptoms',
 'Limonadi_Index_HoarsenessSymptoms',
 'Overall_Hoarseness',
 'Limonadi_Overall_Hoarseness',
 'Refined_HoarsenessSymptoms',
 'Limonadi_HoarsenessSymptoms',
 'Preop_Choking',
 'IndexChokingSymptoms',
 'Limonadi_Index_ChokingSymptoms',
 'Overall_ChokingSymptoms',
 'Limonadi_Overall_ChokingSymptoms',
 'Refined_ChokingSymptoms',
 'Limonadi_ChokingSymptoms',
 'Preop_SleepApnea',
 'IndexSleepApneaSymptoms',
 'Limonadi_Index_SleepApneaSymptoms',
 'Overall_SleepApneaSymptoms',
 'Limonadi_Overall_SleepApneaSymptoms',
 'Refined_SleepApneaSymptoms',
 'Limonadi_SleepApneaSymptoms',
 'Preop_ShortnessOfBreath',
 'IndexSOBSymptoms',
 'Limonadi_Index_SOBSymptoms',
 'Overall_SOBSymptoms',
 'Limonadi_Overall_SOBSymptoms',
 'Refined_SOBSymptoms',
 'Limonadi_SOBSymptoms',
 'Preop_NeckPain',
 'IndexNeckPainSymptoms',
 'Limonadi_Index_NeckPainSymptoms',
 'Overall_NeckPainSymptoms',
 'Limonadi_Overall_NeckPainSymptoms',
 'Refined_NeckPainSymptoms',
 'Limonadi_NeckPainSymptoms',
 'Preop_BackPain',
 'IndexBackPainSymptoms',
 'Limonadi_Index_BackPainSymptoms',
 'Overall_BackPainSymptoms',
 'Limonadi_Overall_BackPainSymptoms',
 'Refined_BackPainSymptoms',
 'Limonadi_BackPainSymptoms',
 'Preop_TrunkPain',
 'IndexTrunkPainSymptoms',
 'Limonadi_Index_TrunkPainSymptoms',
 'Overall_TrunkPainSymptoms',
 'Limonadi_Overall_TrunkPainSymptoms',
 'Refined_TrunkPainSymptoms',
 'Limonadi_TrunkPainSymptoms',
 'Preop_UpperExtremityPain',
 'IndexUpperExtremPainSymptoms',
 'Limonadi_Index_UpperExtremPainSymptoms',
 'Overall_UpperExtPainSymptoms',
 'Limonadi_Overall_UpperExtPainSymptoms',
 'Refined_UpperExtremPainSymptoms',
 'Limonadi_UpperExtremPainSymptoms',
 'Preop_LowerExtremityPain',
 'IndexLowerExtremPainSymptoms',
 'Limonadi_Index_LowerExtremPainSymptoms',
 'Overall_LowerExtPainSymptoms',
 'Limonadi_Overall_LowerExtPainSymptoms',
 'Refined_LowerExtremPainSymptoms',
 'Limonadi_LowerExtremPainSymptoms',
 'Preop_Tremors',
 'IndexTremorsSymptoms',
 'Limonadi_Index_TremorsSymptoms',
 'Overall_TremorsSymptoms',
 'Limonadi_Overall_TremorsSymptoms',
 'Refined_TremorsSymptoms',
 'Limonadi_TremorsSymptoms',
 'Preop_BalanceOrGaitAtaxia',
 'IndexGaitAtaxiaSymptoms',
 'Limonadi_Index_GaitAtaxiaSymptoms',
 'Overall_GaitAtaxiaSymptoms',
 'Limonadi_Overall_GaitAtaxiaSymptoms',
 'Refined_GaitAtaxiaSymptoms',
 'Limonadi_GaitAtaxiaSymptoms',
 'Preop_Incontinence',
 'IndexIncontinenceSymptoms',
 'Limonadi_Index_IncontinenceSymptoms',
 'Overall_IncontinenceSymptoms',
 'Limonadi_Overall_IncontinenceSymptoms',
 'Refined_IncontinenceSymptoms',
 'Limonadi_IncontinenceSymptoms',
 'Preop_SexualDysfunction',
 'IndexSexualDysfunctionSymptoms',
 'Limonadi_Index_SexualDysfunctionSymptoms',
 'Overall_SexualDysfunctionSymp',
 'Limonadi_Overall_SexualDysfunctionSymp',
 'Refined_SexualDysfunctionSymptoms',
 'Limonadi_SexualDysfunctionSymptoms',
 'none_preop']

In [12]:
# desired_column = ['SubjectId',
#  'Papilledema_preop',
#  'Nystagmus_preop',
#  'DisconjugateGaze_preop',
#  'ExtraocularPalsies_preop',
#  'FacialWeakness_preop',
#  'DisturbanceInFacialSensation_preop',
#  'HearingLoss_preop',
#  'Hoarseness_preop',
#  'TongueDeviation_preop',
#  'WeakShrug_preop',
                  
#  'CombinedUpperExtremityWeak_preop',
#  'LeftUpperExtremityWeak_preop',
#  'RightUpperExtremityWeak_preop',
                  
#  'CombinedLowerExtremityWeak_preop',                  
#  'LeftLowerExtremityWeak_preop',
#  'RightLowerExtremityWeak_preop',
                  
#  'LighttouchEntireBody_preop',
                  
#  'CombinedUpperDLTExtremities_preop',                  
#  'DLTLeftUpperExtremities_preop',
#  'DLTRightUpperExtremities_preop',
                  
#  'CombinedLowerDLTExtremities_preop',                  
#  'DLTLeftLowerExtremities_preop',
#  'DLTRightLowerExtremities_preop',

#  'DeficitToPinprickUpperLeft_preop',
#  'DeficitToPinprickUpperRight_preop',
#  'DeficittoPinprickLowerLeft_preop',
#  'DeficittoPinprickLowerRight_preop',
#  'LightTouchTorso_preop',
#  'LightTouchSaddle_preop',
#  'DeepTendonReflexes_preop',
#  'AnkleClonus_preop',
#  'GaitInstability_preop',
#  'Papilledema',
#  'Nystagmus',
#  'DisconjugateGaze',
#  'DocExtraOcPalsies',
#  'FacialWeakness',
#  'DisturbanceFacSen',
#  'HearingLoss',
#  'Hoarseness_x',
#  'TongueDeviation',
#  'WeakShrug',
                  

#  'CombinedUpperExtremityStrength',                  
#  'LeftUpperExtremityStrength',
#  'RightUpperExtremityStrength',

#  'CombinedLowerExtremityStrength',
#  'LeftLowerExtremityStrength',
#  'RightLowerExtremityStrength',
#  'DeficitToLightTouchEntireBody',
                  
#  'CombinedUpperDLTExtremity',
#  'LightTouchSensoryDeficitLUE',
#  'LightTouchSensoryDeficitRUE',
                  
#  'CombinedLowerDLTExtremity',                  
#  'LightTouchSensoryDeficitLLE',
#  'LightTouchSensoryDeficitRLE',
                  
#  'LUEDeficitPinprick',
#  'RUEDeficitPinprick',
#  'LLEDeficitPinprick',
#  'RLEDeficitPinprick',
#  'DeficitLightTouchTorso',
#  'DeepTendonReflexes',
#  'FUAnkleClonus',
#  'GaitStatus',
#  'Site',





#  'Allocation']
# # Flatten the nested list if needed
# if isinstance(desired_column[0], list):
#     desired_column = desired_column[0]

# # Reorder with matching columns only
# existing_cols = [col for col in desired_column if col in pfd_df.columns]

# # Reorder pfd_df
# pfd_df_new = pfd_df[existing_cols]

# # Flatten the nested list if needed
# if isinstance(desired_column[0], list):
#     desired_column = desired_column[0]

# # Reorder with matching columns only
# existing_cols = [col for col in desired_column if col in pfdd_df.columns]

# # Reorder pfd_df
# pfdd_df_new = pfdd_df[existing_cols]

In [13]:
# pfd_df = pfd_df_new.copy()

In [14]:
# pfd_df

In [15]:
# pfdd_df = pfdd_df_.copy()

In [16]:
# list(pfd_df)

In [17]:
# pfd_df['LeftUpperExtremityWeak_preop'].value_counts()

In [18]:
# Function to generate summary table for a given group
def summarize_symptoms(df, label='Group'):
    all_summaries = []

    for pre_symptom, post_symptom in preop_to_refined_neuro_map.items():
        print(pre_symptom)
        # filter with preoperatove data
        pre_symptom = pre_symptom+''
        subset = df[df[pre_symptom] == True]
        baseline_count = subset['SubjectId'].nunique()

        temp = subset[['SubjectId', post_symptom]].fillna(0)
        temp = temp.rename(columns={post_symptom: 'Outcome'})
        temp['Outcome'] = temp['Outcome']
        temp['Symptom'] = pre_symptom
#        print(temp.Outcome.value_counts())
        count_df = temp.groupby('Outcome')['SubjectId'].nunique().reset_index()
        count_df['Symptom'] = pre_symptom
        count_df = count_df.rename(columns={'SubjectId': 'N_Patients'})
        count_pivot = count_df.pivot(index='Symptom', columns='Outcome', values='N_Patients')
        count_pivot['PresentBaseline'] = baseline_count
#        print(count_pivot)
        all_summaries.append(count_pivot)

# ---- Combine Left and Right Extremities ----

    # Define logical groupings of left/right into higher-level symptoms
    combo_groups = {
        'Preop_CombinedUpperExtremityWeak': ['Preop_LeftUpperExtremityWeak', 'Preop_RightUpperExtremityWeak'],
        'Preop_CombinedLowerExtremityWeak': ['Preop_LeftLowerExtremityWeak', 'Preop_RightLowerExtremityWeak'],
        'Preop_CombinedUpperDLTExtremity': ['Preop_DLTLeftUpperExtremities', 'Preop_DLTRightUpperExtremities'],
        'Preop_CombinedLowerDLTExtremity': ['Preop_DLTLeftLowerExtremities', 'Preop_DLTRightLowerExtremities'],
    }

    for new_symptom, sub_symptoms in combo_groups.items():
        # Get preop columns
        preop_cols = [s + "" for s in sub_symptoms]

        # Subjects who had any pre-op indication
        patients_union = set()
        for col in preop_cols:
            patients_union |= set(df[df[col] == True]['SubjectId'])

        baseline_count = len(patients_union)

        # Get corresponding post-op column names from neuro_sign_map
        postop_cols = [preop_to_refined_neuro_map[s] for s in sub_symptoms]

        # Get the actual data
        subset = df[df['SubjectId'].isin(patients_union)][['SubjectId'] + postop_cols].fillna(0)

        # Use max value across post-op indicators
        subset['Outcome'] = subset[postop_cols].max(axis=1)
        subset['Symptom'] = new_symptom
        print(subset)
        print(subset.columns)
        # Count distinct subjects per outcome category
        count_df = subset.groupby('Outcome')['SubjectId'].nunique().reset_index()

        count_df['Symptom'] = new_symptom
        count_df = count_df.rename(columns={'SubjectId': 'N_Patients'})
        count_pivot = count_df.pivot(index='Symptom', columns='Outcome', values='N_Patients').fillna(0)
        count_pivot['PresentBaseline'] = baseline_count

        all_summaries.append(count_pivot)

    outcome_labels = {
        1: 'Resolved',
        2: 'Improved',
        3: 'Stable',
        4: 'Worse',
        5: 'Unknown',
        'Nan in the datasheets':'Nan in the datasheets',
        '2': 'Improved',
        '0':'Unknown',
        '1':'Resolved',
        '3':'Stable',
        '4':'Worse'
    }

    # 5. Reorder columns (only include if present)
    desired_order = [
        'PresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse',
        'Unknown','Nan in the datasheets'
    ]

    # Combine and rename
    summary_df = pd.concat(all_summaries).fillna(0)

#     summary_df = summary_df.replace({
#     '1': 1,
#     '2': 2,
#     '3': 3,
#         '4':4,
#         '0':0
# })
    summary_df = summary_df.rename(columns=outcome_labels)

    # Reorder
    summary_df = summary_df[[col for col in desired_order if col in summary_df.columns]]
    summary_df = summary_df.reset_index()
    summary_df['Group'] = label

    return summary_df,subset


# Apply separately to each group
pfd_summary,pfd_subset = summarize_symptoms(pfd_df, label='PFD')
print('======================================================split betwwen pfd and pfdd============================================================================================')
pfdd_summary,pfdd_subset = summarize_symptoms(pfdd_df, label='PFDD')


pfd_summary

Preop_Papilledema
Preop_Nystagmus
Preop_DisconjugateGaze
Preop_ExtraocularPalsies
Preop_FacialWeakness
Preop_DisturbanceInFacialSensation
Preop_HearingLoss
Preop_Hoarseness_x
Preop_TongueDeviation
Preop_WeakShrug
Preop_LeftUpperExtremityWeak
Preop_RightUpperExtremityWeak
Preop_LeftLowerExtremityWeak
Preop_RightLowerExtremityWeak
Preop_LighttouchEntireBody
Preop_DLTLeftUpperExtremities
Preop_DLTRightUpperExtremities
Preop_DLTLeftLowerExtremities
Preop_DLTRightLowerExtremities
Preop_DeficitToPinprickUpperLeft
Preop_DeficitToPinprickUpperRight
Preop_DeficittoPinprickLowerLeft
Preop_DeficittoPinprickLowerRight
Preop_LightTouchTorso
Preop_LightTouchSaddle
Preop_DeepTendonReflexes
Preop_AnkleClonus
Preop_GaitInstability
    SubjectId  Refined_LeftUpperExtremityStrength  \
30         33                                 3.0
79         82                                 1.0

    Refined_RightUpperExtremityStrength  Outcome  \
30                                  1.0      3.0
79                                  3.0      3.0

                             Symptom
30  Preop_CombinedUpperExtremityWeak
79  Preop_CombinedUpperExtremityWeak
Index(['SubjectId', 'Refined_LeftUpperExtremityStrength',
       'Refined_RightUpperExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
Empty DataFrame
Columns: [SubjectId, Refined_LeftLowerExtremityStrength, Refined_RightLowerExtremityStrength, Outcome, Symptom]
Index: []
Index(['SubjectId', 'Refined_LeftLowerExtremityStrength',
       'Refined_RightLowerExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
    SubjectId  Refined_LightTouchSensoryDeficitLUE  \
30         33                                  3.0
79         82                                  1.0

    Refined_LightTouchSensoryDeficitRUE  Outcome  \
30                                  1.0      3.0
79                                  3.0      3.0

                            Symptom
30  Preop_CombinedUpperDLTExtremity
79  Preop_CombinedUpperDLTExtremity
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLUE',
       'Refined_LightTouchSensoryDeficitRUE', 'Outcome', 'Symptom'],
      dtype='object')
Empty DataFrame
Columns: [SubjectId, Refined_LightTouchSensoryDeficitLLE, Refined_LightTouchSensoryDeficitRLE, Outcome, Symptom]
Index: []
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLLE',
       'Refined_LightTouchSensoryDeficitRLE', 'Outcome', 'Symptom'],
      dtype='object')
======================================================split betwwen pfd and pfdd============================================================================================
Preop_Papilledema
Preop_Nystagmus
Preop_DisconjugateGaze
Preop_ExtraocularPalsies
Preop_FacialWeakness
Preop_DisturbanceInFacialSensation
Preop_HearingLoss
Preop_Hoarseness_x
Preop_TongueDeviation
Preop_WeakShrug
Preop_LeftUpperExtremityWeak
Preop_RightUpperExtremityWeak
Preop_LeftLowerExtremityWeak
Preop_RightLowerExtremityWeak
Preop_LighttouchEntireBody
Preop_DLTLeftUpperExtremities
Preop_DLTRightUpperExtremities
Preop_DLTLeftLowerExtremities
Preop_DLTRightLowerExtremities
Preop_DeficitToPinprickUpperLeft
Preop_DeficitToPinprickUpperRight
Preop_DeficittoPinprickLowerLeft
Preop_DeficittoPinprickLowerRight
Preop_LightTouchTorso
Preop_LightTouchSaddle
Preop_DeepTendonReflexes
Preop_AnkleClonus
Preop_GaitInstability
     SubjectId  Refined_LeftUpperExtremityStrength  \
123        126                                 3.0
129        132                                 3.0

     Refined_RightUpperExtremityStrength  Outcome  \
123                                  1.0      3.0
129                                  2.0      3.0

                              Symptom
123  Preop_CombinedUpperExtremityWeak
129  Preop_CombinedUpperExtremityWeak
Index(['SubjectId', 'Refined_LeftUpperExtremityStrength',
       'Refined_RightUpperExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
Empty DataFrame
Columns: [SubjectId, Refined_LeftLowerExtremityStrength, Refined_RightLowerExtremityStrength, Outcome, Symptom]
Index: []
Index(['SubjectId', 'Refined_LeftLowerExtremityStrength',
       'Refined_RightLowerExtremityStrength', 'Outcome', 'Symptom'],
      dtype='object')
    SubjectId  Refined_LightTouchSensoryDeficitLUE  \
47         50                                  3.0
81         84                                  3.0
97        100                                  2.0

    Refined_LightTouchSensoryDeficitRUE  Outcome  \
47                                  1.0      3.0
81                                  3.0      3.0
97                                  2.0      2.0

                            Symptom
47  Preop_CombinedUpperDLTExtremity
81  Preop_CombinedUpperDLTExtremity
97  Preop_CombinedUpperDLTExtremity
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLUE',
       'Refined_LightTouchSensoryDeficitRUE', 'Outcome', 'Symptom'],
      dtype='object')
Empty DataFrame
Columns: [SubjectId, Refined_LightTouchSensoryDeficitLLE, Refined_LightTouchSensoryDeficitRLE, Outcome, Symptom]
Index: []
Index(['SubjectId', 'Refined_LightTouchSensoryDeficitLLE',
       'Refined_LightTouchSensoryDeficitRLE', 'Outcome', 'Symptom'],
      dtype='object')

Outcome,Symptom,PresentBaseline,Resolved,Stable,Worse,Unknown,Group
0,Preop_Papilledema,1,0.0,0.0,0.0,1.0,PFD
1,Preop_Nystagmus,4,2.0,1.0,1.0,0.0,PFD
2,Preop_DisconjugateGaze,1,1.0,0.0,0.0,0.0,PFD
3,Preop_ExtraocularPalsies,2,2.0,0.0,0.0,0.0,PFD
4,Preop_DisturbanceInFacialSensation,1,1.0,0.0,0.0,0.0,PFD
5,Preop_HearingLoss,1,1.0,0.0,0.0,0.0,PFD
6,Preop_Hoarseness_x,2,1.0,0.0,0.0,1.0,PFD
7,Preop_LeftUpperExtremityWeak,1,1.0,0.0,0.0,0.0,PFD
8,Preop_RightUpperExtremityWeak,1,1.0,0.0,0.0,0.0,PFD
9,Preop_DLTLeftUpperExtremities,1,1.0,0.0,0.0,0.0,PFD
10,Preop_DLTRightUpperExtremities,1,1.0,0.0,0.0,0.0,PFD
11,Preop_DeepTendonReflexes,1,0.0,0.0,0.0,1.0,PFD
12,Preop_AnkleClonus,2,1.0,0.0,0.0,1.0,PFD
13,Preop_GaitInstability,4,3.0,0.0,0.0,1.0,PFD
14,Preop_CombinedUpperExtremityWeak,2,0.0,2.0,0.0,0.0,PFD
15,Preop_CombinedUpperDLTExtremity,2,0.0,2.0,0.0,0.0,PFD

In [19]:
pfd_summary

Outcome,Symptom,PresentBaseline,Resolved,Stable,Worse,Unknown,Group
0,Preop_Papilledema,1,0.0,0.0,0.0,1.0,PFD
1,Preop_Nystagmus,4,2.0,1.0,1.0,0.0,PFD
2,Preop_DisconjugateGaze,1,1.0,0.0,0.0,0.0,PFD
3,Preop_ExtraocularPalsies,2,2.0,0.0,0.0,0.0,PFD
4,Preop_DisturbanceInFacialSensation,1,1.0,0.0,0.0,0.0,PFD
5,Preop_HearingLoss,1,1.0,0.0,0.0,0.0,PFD
6,Preop_Hoarseness_x,2,1.0,0.0,0.0,1.0,PFD
7,Preop_LeftUpperExtremityWeak,1,1.0,0.0,0.0,0.0,PFD
8,Preop_RightUpperExtremityWeak,1,1.0,0.0,0.0,0.0,PFD
9,Preop_DLTLeftUpperExtremities,1,1.0,0.0,0.0,0.0,PFD
10,Preop_DLTRightUpperExtremities,1,1.0,0.0,0.0,0.0,PFD
11,Preop_DeepTendonReflexes,1,0.0,0.0,0.0,1.0,PFD
12,Preop_AnkleClonus,2,1.0,0.0,0.0,1.0,PFD
13,Preop_GaitInstability,4,3.0,0.0,0.0,1.0,PFD
14,Preop_CombinedUpperExtremityWeak,2,0.0,2.0,0.0,0.0,PFD
15,Preop_CombinedUpperDLTExtremity,2,0.0,2.0,0.0,0.0,PFD

In [20]:
# Define all outcome-related columns to sum
outcome_cols = [
    'Resolved',
    'Improved',
    'Stable',
    'Worse',
    'Unknown',
# 'Nan in the datasheets'
#     'Nan in the datasheets'
]
for col in outcome_cols:
    if col not in pfd_summary.columns:
        pfd_summary[col] = 0.0

pfd_summary['TotalCounted'] = pfd_summary[outcome_cols].sum(axis=1)
pfd_summary['equal'] = pfd_summary['TotalCounted'] == pfd_summary['PresentBaseline'] 
pfd_summary

Outcome,Symptom,PresentBaseline,Resolved,Stable,Worse,Unknown,Group,Improved,TotalCounted,equal
0,Preop_Papilledema,1,0.0,0.0,0.0,1.0,PFD,0.0,1.0,True
1,Preop_Nystagmus,4,2.0,1.0,1.0,0.0,PFD,0.0,4.0,True
2,Preop_DisconjugateGaze,1,1.0,0.0,0.0,0.0,PFD,0.0,1.0,True
3,Preop_ExtraocularPalsies,2,2.0,0.0,0.0,0.0,PFD,0.0,2.0,True
4,Preop_DisturbanceInFacialSensation,1,1.0,0.0,0.0,0.0,PFD,0.0,1.0,True
5,Preop_HearingLoss,1,1.0,0.0,0.0,0.0,PFD,0.0,1.0,True
6,Preop_Hoarseness_x,2,1.0,0.0,0.0,1.0,PFD,0.0,2.0,True
7,Preop_LeftUpperExtremityWeak,1,1.0,0.0,0.0,0.0,PFD,0.0,1.0,True
8,Preop_RightUpperExtremityWeak,1,1.0,0.0,0.0,0.0,PFD,0.0,1.0,True
9,Preop_DLTLeftUpperExtremities,1,1.0,0.0,0.0,0.0,PFD,0.0,1.0,True
10,Preop_DLTRightUpperExtremities,1,1.0,0.0,0.0,0.0,PFD,0.0,1.0,True
11,Preop_DeepTendonReflexes,1,0.0,0.0,0.0,1.0,PFD,0.0,1.0,True
12,Preop_AnkleClonus,2,1.0,0.0,0.0,1.0,PFD,0.0,2.0,True
13,Preop_GaitInstability,4,3.0,0.0,0.0,1.0,PFD,0.0,4.0,True
14,Preop_CombinedUpperExtremityWeak,2,0.0,2.0,0.0,0.0,PFD,0.0,2.0,True
15,Preop_CombinedUpperDLTExtremity,2,0.0,2.0,0.0,0.0,PFD,0.0,2.0,True

In [21]:
combo_groups = {
    'Preop_CombinedUpperExtremityWeak': ['Preop_LeftUpperExtremityWeak', 'Preop_RightUpperExtremityWeak'],
    'Preop_CombinedLowerExtremityWeak': ['Preop_LeftLowerExtremityWeak', 'Preop_RightLowerExtremityWeak'],
    'Preop_CombinedUpperDLTExtremity': ['Preop_DLTLeftUpperExtremities', 'Preop_DLTRightUpperExtremities'],
    'Preop_CombinedLowerDLTExtremity': ['Preop_DLTLeftLowerExtremities', 'Preop_DLTRightLowerExtremities'],
}
desired_order = [
    'Papilledema', 'Nystagmus', 'DisconjugateGaze', 'ExtraocularPalsies',
    'FacialWeakness', 'DisturbanceInFacialSensation', 'HearingLoss',
    'Hoarseness', 'TongueDeviation', 'WeakShrug',

    'CombinedUpperExtremityWeak', 'LeftUpperExtremityWeak', 'RightUpperExtremityWeak',
    'CombinedLowerExtremityWeak', 'LeftLowerExtremityWeak', 'RightLowerExtremityWeak',

    'LighttouchEntireBody',
    'CombinedUpperDLTExtremity', 'DLTLeftUpperExtremities', 'DLTRightUpperExtremities',
    'CombinedLowerDLTExtremity', 'DLTLeftLowerExtremities', 'DLTRightLowerExtremities',

    'DeficitToPinprickUpperLeft', 'DeficitToPinprickUpperRight',
    'DeficittoPinprickLowerLeft', 'DeficittoPinprickLowerRight',
    'LightTouchTorso', 'LightTouchSaddle',
    'DeepTendonReflexes', 'AnkleClonus', 'GaitInstability'
]
desired_order = ['Preop_'+s for s in desired_order]
# Create a mapping from symptom to its desired sort order
order_map = {symptom: i for i, symptom in enumerate(desired_order)}


# Add a sort index column
pfd_summary['sort_order'] = pfd_summary['Symptom'].map(order_map)

# Sort and clean up
pfd_summary = pfd_summary.sort_values(by='sort_order').drop(columns='sort_order').reset_index(drop=True)

pfd_summary['sort_order'] = pfd_summary['Symptom'].map(order_map)

# Sort and clean up
pfd_summary_ordered = pfd_summary.sort_values(by='sort_order').drop(columns='sort_order').reset_index(drop=True)

# Ensure all needed columns exist
required_columns = ['Symptom', 'PresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'Group', 'TotalCounted', 'equal']
for col in required_columns:
    if col not in pfd_summary.columns:
        pfd_summary[col] = 0

# Set index to 'Symptom' for easy reindexing
pfd_summary.set_index('Symptom', inplace=True)

# Reindex with desired order and fill all missing values with NaN (temporarily)
pfd_summary_ordered = pfd_summary.reindex(desired_order).reset_index()

# Fill missing values in specific columns first
pfd_summary_ordered['Group'] = pfd_summary_ordered['Group'].fillna('PFD')
pfd_summary_ordered['equal'] = pfd_summary_ordered['equal'].fillna(True)

# Fill remaining numeric columns with 0
pfd_summary_ordered.fillna(0, inplace=True)



# Convert appropriate columns to integers (if needed)
int_cols = ['PresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'TotalCounted']
pfd_summary_ordered[int_cols] = pfd_summary_ordered[int_cols].astype(int)

/var/folders/5b/z7m8dzcs5td_8q7jrcf_9spm0000gn/T/ipykernel_3559/2380146271.py:54: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pfd_summary_ordered['equal'] = pfd_summary_ordered['equal'].fillna(True)

In [22]:
desired_order = [
    'Papilledema', 'Nystagmus', 'DisconjugateGaze', 'ExtraocularPalsies',
    'FacialWeakness', 'DisturbanceInFacialSensation', 'HearingLoss',
    'Hoarseness', 'TongueDeviation', 'WeakShrug',

    'CombinedUpperExtremityWeak', 'LeftUpperExtremityWeak', 'RightUpperExtremityWeak',
    'CombinedLowerExtremityWeak', 'LeftLowerExtremityWeak', 'RightLowerExtremityWeak',

    'LighttouchEntireBody',
    'CombinedUpperDLTExtremity', 'DLTLeftUpperExtremities', 'DLTRightUpperExtremities',
    'CombinedLowerDLTExtremity', 'DLTLeftLowerExtremities', 'DLTRightLowerExtremities',

    'DeficitToPinprickUpperLeft', 'DeficitToPinprickUpperRight',
    'DeficittoPinprickLowerLeft', 'DeficittoPinprickLowerRight',
    'LightTouchTorso', 'LightTouchSaddle',
    'DeepTendonReflexes', 'AnkleClonus', 'GaitInstability'
]
desired_order = ['Preop_'+s for s in desired_order]
# Create a mapping from symptom to its desired sort order
order_map = {symptom: i for i, symptom in enumerate(desired_order)}


# Add a sort index column
pfdd_summary['sort_order'] = pfdd_summary['Symptom'].map(order_map)

# Sort and clean up
pfdd_summary = pfdd_summary.sort_values(by='sort_order').drop(columns='sort_order').reset_index(drop=True)

pfdd_summary['sort_order'] = pfdd_summary['Symptom'].map(order_map)

# Sort and clean up
pfdd_summary_ordered = pfdd_summary.sort_values(by='sort_order').drop(columns='sort_order').reset_index(drop=True)

In [23]:
pfd_summary_ordered

Outcome,Symptom,PresentBaseline,Resolved,Stable,Worse,Unknown,Group,Improved,TotalCounted,equal,sort_order
0,Preop_Papilledema,1,0,0,0,1,PFD,0,1,True,0.0
1,Preop_Nystagmus,4,2,1,1,0,PFD,0,4,True,1.0
2,Preop_DisconjugateGaze,1,1,0,0,0,PFD,0,1,True,2.0
3,Preop_ExtraocularPalsies,2,2,0,0,0,PFD,0,2,True,3.0
4,Preop_FacialWeakness,0,0,0,0,0,PFD,0,0,True,0.0
5,Preop_DisturbanceInFacialSensation,1,1,0,0,0,PFD,0,1,True,5.0
6,Preop_HearingLoss,1,1,0,0,0,PFD,0,1,True,6.0
7,Preop_Hoarseness,0,0,0,0,0,PFD,0,0,True,0.0
8,Preop_TongueDeviation,0,0,0,0,0,PFD,0,0,True,0.0
9,Preop_WeakShrug,0,0,0,0,0,PFD,0,0,True,0.0
10,Preop_CombinedUpperExtremityWeak,2,0,2,0,0,PFD,0,2,True,10.0
11,Preop_LeftUpperExtremityWeak,1,1,0,0,0,PFD,0,1,True,11.0
12,Preop_RightUpperExtremityWeak,1,1,0,0,0,PFD,0,1,True,12.0
13,Preop_CombinedLowerExtremityWeak,0,0,0,0,0,PFD,0,0,True,0.0
14,Preop_LeftLowerExtremityWeak,0,0,0,0,0,PFD,0,0,True,0.0
15,Preop_RightLowerExtremityWeak,0,0,0,0,0,PFD,0,0,True,0.0
16,Preop_LighttouchEntireBody,0,0,0,0,0,PFD,0,0,True,0.0
17,Preop_CombinedUpperDLTExtremity,2,0,2,0,0,PFD,0,2,True,17.0
18,Preop_DLTLeftUpperExtremities,1,1,0,0,0,PFD,0,1,True,18.0
19,Preop_DLTRightUpperExtremities,1,1,0,0,0,PFD,0,1,True,19.0
20,Preop_CombinedLowerDLTExtremity,0,0,0,0,0,PFD,0,0,True,0.0
21,Preop_DLTLeftLowerExtremities,0,0,0,0,0,PFD,0,0,True,0.0
22,Preop_DLTRightLowerExtremities,0,0,0,0,0,PFD,0,0,True,0.0
23,Preop_DeficitToPinprickUpperLeft,0,0,0,0,0,PFD,0,0,True,0.0
24,Preop_DeficitToPinprickUpperRight,0,0,0,0,0,PFD,0,0,True,0.0
25,Preop_DeficittoPinprickLowerLeft,0,0,0,0,0,PFD,0,0,True,0.0
26,Preop_DeficittoPinprickLowerRight,0,0,0,0,0,PFD,0,0,True,0.0
27,Preop_LightTouchTorso,0,0,0,0,0,PFD,0,0,True,0.0
28,Preop_LightTouchSaddle,0,0,0,0,0,PFD,0,0,True,0.0
29,Preop_DeepTendonReflexes,1,0,0,0,1,PFD,0,1,True,29.0
30,Preop_AnkleClonus,2,1,0,0,1,PFD,0,2,True,30.0
31,Preop_GaitInstability,4,3,0,0,1,PFD,0,4,True,31.0

In [24]:
pfdd_summary_ordered

Outcome,Symptom,PresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Group
0,Preop_Papilledema,1,0.0,0.0,1.0,0.0,0.0,PFDD
1,Preop_Nystagmus,5,1.0,0.0,1.0,0.0,3.0,PFDD
2,Preop_DisconjugateGaze,1,0.0,0.0,1.0,0.0,0.0,PFDD
3,Preop_ExtraocularPalsies,2,1.0,0.0,1.0,0.0,0.0,PFDD
4,Preop_HearingLoss,1,0.0,0.0,0.0,0.0,1.0,PFDD
5,Preop_CombinedUpperExtremityWeak,2,0.0,0.0,2.0,0.0,0.0,PFDD
6,Preop_RightUpperExtremityWeak,2,1.0,1.0,0.0,0.0,0.0,PFDD
7,Preop_CombinedUpperDLTExtremity,3,0.0,1.0,2.0,0.0,0.0,PFDD
8,Preop_DLTLeftUpperExtremities,2,0.0,1.0,1.0,0.0,0.0,PFDD
9,Preop_DLTRightUpperExtremities,2,1.0,1.0,0.0,0.0,0.0,PFDD
10,Preop_DeepTendonReflexes,7,0.0,0.0,0.0,1.0,6.0,PFDD
11,Preop_AnkleClonus,1,0.0,0.0,0.0,0.0,1.0,PFDD
12,Preop_GaitInstability,9,2.0,0.0,0.0,2.0,5.0,PFDD
13,Preop_Hoarseness_x,1,0.0,0.0,0.0,0.0,1.0,PFDD

In [25]:

required_columns = ['Symptom', 'PresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'Group', 'TotalCounted', 'equal']
for col in required_columns:
    if col not in pfdd_summary.columns:
        pfdd_summary[col] = 0

# Set index to 'Symptom' for easy reindexing
pfdd_summary.set_index('Symptom', inplace=True)

# Reindex with desired order and fill all missing values with NaN (temporarily)
pfdd_summary_ordered = pfdd_summary.reindex(desired_order).reset_index()

# Fill missing values in specific columns first
pfdd_summary_ordered['Group'] = pfdd_summary_ordered['Group'].fillna('PFDD')
pfdd_summary_ordered['equal'] = pfdd_summary_ordered['equal'].fillna(True)

# Fill remaining numeric columns with 0
pfdd_summary_ordered.fillna(0, inplace=True)



# Convert appropriate columns to integers (if needed)
int_cols = ['PresentBaseline', 'Resolved', 'Improved', 'Stable', 'Worse', 'Unknown', 'TotalCounted']
pfdd_summary_ordered[int_cols] = pfdd_summary_ordered[int_cols].astype(int)

In [26]:
# Define all outcome-related columns to sum
outcome_cols = [
    'Resolved',
    'Improved',
    'Stable',
    'Worse',
    'Unknown',
# 'Nan in the datasheets'
#     'Nan in the datasheets'
]

# Check for mismatches in PFDD
pfdd_summary_ordered['TotalCounted'] = pfdd_summary_ordered[outcome_cols].sum(axis=1)
pfdd_summary_ordered['equal'] = pfdd_summary_ordered['TotalCounted'] == pfdd_summary_ordered['PresentBaseline']

In [27]:
pfdd_summary_ordered

Outcome,Symptom,PresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Group,sort_order,TotalCounted,equal
0,Preop_Papilledema,1,0,0,1,0,0,PFDD,0.0,1,True
1,Preop_Nystagmus,5,1,0,1,0,3,PFDD,1.0,5,True
2,Preop_DisconjugateGaze,1,0,0,1,0,0,PFDD,2.0,1,True
3,Preop_ExtraocularPalsies,2,1,0,1,0,0,PFDD,3.0,2,True
4,Preop_FacialWeakness,0,0,0,0,0,0,PFDD,0.0,0,True
5,Preop_DisturbanceInFacialSensation,0,0,0,0,0,0,PFDD,0.0,0,True
6,Preop_HearingLoss,1,0,0,0,0,1,PFDD,6.0,1,True
7,Preop_Hoarseness,0,0,0,0,0,0,PFDD,0.0,0,True
8,Preop_TongueDeviation,0,0,0,0,0,0,PFDD,0.0,0,True
9,Preop_WeakShrug,0,0,0,0,0,0,PFDD,0.0,0,True
10,Preop_CombinedUpperExtremityWeak,2,0,0,2,0,0,PFDD,10.0,2,True
11,Preop_LeftUpperExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
12,Preop_RightUpperExtremityWeak,2,1,1,0,0,0,PFDD,12.0,2,True
13,Preop_CombinedLowerExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
14,Preop_LeftLowerExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
15,Preop_RightLowerExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
16,Preop_LighttouchEntireBody,0,0,0,0,0,0,PFDD,0.0,0,True
17,Preop_CombinedUpperDLTExtremity,3,0,1,2,0,0,PFDD,17.0,3,True
18,Preop_DLTLeftUpperExtremities,2,0,1,1,0,0,PFDD,18.0,2,True
19,Preop_DLTRightUpperExtremities,2,1,1,0,0,0,PFDD,19.0,2,True
20,Preop_CombinedLowerDLTExtremity,0,0,0,0,0,0,PFDD,0.0,0,True
21,Preop_DLTLeftLowerExtremities,0,0,0,0,0,0,PFDD,0.0,0,True
22,Preop_DLTRightLowerExtremities,0,0,0,0,0,0,PFDD,0.0,0,True
23,Preop_DeficitToPinprickUpperLeft,0,0,0,0,0,0,PFDD,0.0,0,True
24,Preop_DeficitToPinprickUpperRight,0,0,0,0,0,0,PFDD,0.0,0,True
25,Preop_DeficittoPinprickLowerLeft,0,0,0,0,0,0,PFDD,0.0,0,True
26,Preop_DeficittoPinprickLowerRight,0,0,0,0,0,0,PFDD,0.0,0,True
27,Preop_LightTouchTorso,0,0,0,0,0,0,PFDD,0.0,0,True
28,Preop_LightTouchSaddle,0,0,0,0,0,0,PFDD,0.0,0,True
29,Preop_DeepTendonReflexes,7,0,0,0,1,6,PFDD,29.0,7,True
30,Preop_AnkleClonus,1,0,0,0,0,1,PFDD,30.0,1,True
31,Preop_GaitInstability,9,2,0,0,2,5,PFDD,31.0,9,True

In [28]:
pfd_summary_ordered.to_csv('250930_preop_pfd_summary_table2_neurological_exam.csv',index=False)

In [29]:
pfdd_summary_ordered.to_csv('250930_preoppfdd_summary_table2_neurological_exam.csv',index=False)

In [30]:
pfd_summary_ordered

Outcome,Symptom,PresentBaseline,Resolved,Stable,Worse,Unknown,Group,Improved,TotalCounted,equal,sort_order
0,Preop_Papilledema,1,0,0,0,1,PFD,0,1,True,0.0
1,Preop_Nystagmus,4,2,1,1,0,PFD,0,4,True,1.0
2,Preop_DisconjugateGaze,1,1,0,0,0,PFD,0,1,True,2.0
3,Preop_ExtraocularPalsies,2,2,0,0,0,PFD,0,2,True,3.0
4,Preop_FacialWeakness,0,0,0,0,0,PFD,0,0,True,0.0
5,Preop_DisturbanceInFacialSensation,1,1,0,0,0,PFD,0,1,True,5.0
6,Preop_HearingLoss,1,1,0,0,0,PFD,0,1,True,6.0
7,Preop_Hoarseness,0,0,0,0,0,PFD,0,0,True,0.0
8,Preop_TongueDeviation,0,0,0,0,0,PFD,0,0,True,0.0
9,Preop_WeakShrug,0,0,0,0,0,PFD,0,0,True,0.0
10,Preop_CombinedUpperExtremityWeak,2,0,2,0,0,PFD,0,2,True,10.0
11,Preop_LeftUpperExtremityWeak,1,1,0,0,0,PFD,0,1,True,11.0
12,Preop_RightUpperExtremityWeak,1,1,0,0,0,PFD,0,1,True,12.0
13,Preop_CombinedLowerExtremityWeak,0,0,0,0,0,PFD,0,0,True,0.0
14,Preop_LeftLowerExtremityWeak,0,0,0,0,0,PFD,0,0,True,0.0
15,Preop_RightLowerExtremityWeak,0,0,0,0,0,PFD,0,0,True,0.0
16,Preop_LighttouchEntireBody,0,0,0,0,0,PFD,0,0,True,0.0
17,Preop_CombinedUpperDLTExtremity,2,0,2,0,0,PFD,0,2,True,17.0
18,Preop_DLTLeftUpperExtremities,1,1,0,0,0,PFD,0,1,True,18.0
19,Preop_DLTRightUpperExtremities,1,1,0,0,0,PFD,0,1,True,19.0
20,Preop_CombinedLowerDLTExtremity,0,0,0,0,0,PFD,0,0,True,0.0
21,Preop_DLTLeftLowerExtremities,0,0,0,0,0,PFD,0,0,True,0.0
22,Preop_DLTRightLowerExtremities,0,0,0,0,0,PFD,0,0,True,0.0
23,Preop_DeficitToPinprickUpperLeft,0,0,0,0,0,PFD,0,0,True,0.0
24,Preop_DeficitToPinprickUpperRight,0,0,0,0,0,PFD,0,0,True,0.0
25,Preop_DeficittoPinprickLowerLeft,0,0,0,0,0,PFD,0,0,True,0.0
26,Preop_DeficittoPinprickLowerRight,0,0,0,0,0,PFD,0,0,True,0.0
27,Preop_LightTouchTorso,0,0,0,0,0,PFD,0,0,True,0.0
28,Preop_LightTouchSaddle,0,0,0,0,0,PFD,0,0,True,0.0
29,Preop_DeepTendonReflexes,1,0,0,0,1,PFD,0,1,True,29.0
30,Preop_AnkleClonus,2,1,0,0,1,PFD,0,2,True,30.0
31,Preop_GaitInstability,4,3,0,0,1,PFD,0,4,True,31.0

In [31]:
pfdd_summary_ordered

Outcome,Symptom,PresentBaseline,Resolved,Improved,Stable,Worse,Unknown,Group,sort_order,TotalCounted,equal
0,Preop_Papilledema,1,0,0,1,0,0,PFDD,0.0,1,True
1,Preop_Nystagmus,5,1,0,1,0,3,PFDD,1.0,5,True
2,Preop_DisconjugateGaze,1,0,0,1,0,0,PFDD,2.0,1,True
3,Preop_ExtraocularPalsies,2,1,0,1,0,0,PFDD,3.0,2,True
4,Preop_FacialWeakness,0,0,0,0,0,0,PFDD,0.0,0,True
5,Preop_DisturbanceInFacialSensation,0,0,0,0,0,0,PFDD,0.0,0,True
6,Preop_HearingLoss,1,0,0,0,0,1,PFDD,6.0,1,True
7,Preop_Hoarseness,0,0,0,0,0,0,PFDD,0.0,0,True
8,Preop_TongueDeviation,0,0,0,0,0,0,PFDD,0.0,0,True
9,Preop_WeakShrug,0,0,0,0,0,0,PFDD,0.0,0,True
10,Preop_CombinedUpperExtremityWeak,2,0,0,2,0,0,PFDD,10.0,2,True
11,Preop_LeftUpperExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
12,Preop_RightUpperExtremityWeak,2,1,1,0,0,0,PFDD,12.0,2,True
13,Preop_CombinedLowerExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
14,Preop_LeftLowerExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
15,Preop_RightLowerExtremityWeak,0,0,0,0,0,0,PFDD,0.0,0,True
16,Preop_LighttouchEntireBody,0,0,0,0,0,0,PFDD,0.0,0,True
17,Preop_CombinedUpperDLTExtremity,3,0,1,2,0,0,PFDD,17.0,3,True
18,Preop_DLTLeftUpperExtremities,2,0,1,1,0,0,PFDD,18.0,2,True
19,Preop_DLTRightUpperExtremities,2,1,1,0,0,0,PFDD,19.0,2,True
20,Preop_CombinedLowerDLTExtremity,0,0,0,0,0,0,PFDD,0.0,0,True
21,Preop_DLTLeftLowerExtremities,0,0,0,0,0,0,PFDD,0.0,0,True
22,Preop_DLTRightLowerExtremities,0,0,0,0,0,0,PFDD,0.0,0,True
23,Preop_DeficitToPinprickUpperLeft,0,0,0,0,0,0,PFDD,0.0,0,True
24,Preop_DeficitToPinprickUpperRight,0,0,0,0,0,0,PFDD,0.0,0,True
25,Preop_DeficittoPinprickLowerLeft,0,0,0,0,0,0,PFDD,0.0,0,True
26,Preop_DeficittoPinprickLowerRight,0,0,0,0,0,0,PFDD,0.0,0,True
27,Preop_LightTouchTorso,0,0,0,0,0,0,PFDD,0.0,0,True
28,Preop_LightTouchSaddle,0,0,0,0,0,0,PFDD,0.0,0,True
29,Preop_DeepTendonReflexes,7,0,0,0,1,6,PFDD,29.0,7,True
30,Preop_AnkleClonus,1,0,0,0,0,1,PFDD,30.0,1,True
31,Preop_GaitInstability,9,2,0,0,2,5,PFDD,31.0,9,True